//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.03 at 12:32:33 PM CDT 
//


package com.optum.enterprise.schema.cim.api.finance.payables.provider.paymentsservice_v1_0;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;
import com.optum.enterprise.schema.cim.api.finance.payables.provider.epspaymentmaintenanceservice_v1_0.EpsClaimPaymentResponse;
import com.optum.enterprise.schema.cim.api.finance.payables.provider.epspaymentmaintenanceservice_v1_0.EpsConsolidatedClaimPaymentDetail;
import com.optum.enterprise.schema.cim.api.finance.payables.provider.epspaymentmaintenanceservice_v1_0.EpsPaymentStatusCode;
import com.optum.enterprise.schema.cim.common.code_v1_0.BaseCode;
import com.optum.enterprise.schema.cim.common.common_v1_0.Currency;
import com.optum.enterprise.schema.cim.common.payment_v1_0.Payment;


/**
 * <p>Java class for EpsConsolidatedClaimPaymentSummary complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EpsConsolidatedClaimPaymentSummary">
 *   &lt;complexContent>
 *     &lt;extension base="{http://enterprise.optum.com/schema/cim/common/Payment_v1_0}Payment">
 *       &lt;sequence>
 *         &lt;element ref="{http://enterprise.optum.com/schema/cim/common/Common_v1_0}SchemaName"/>
 *         &lt;element ref="{http://enterprise.optum.com/schema/cim/api/finance/payables/provider/EpsPaymentMaintenanceService_v1_0}DisplayConsolidatedPaymentNumber"/>
 *         &lt;element ref="{http://enterprise.optum.com/schema/cim/api/finance/payables/provider/EpsPaymentMaintenanceService_v1_0}ConsolidatedPaymentNumber"/>
 *         &lt;element ref="{http://enterprise.optum.com/schema/cim/api/finance/payables/provider/EpsPaymentMaintenanceService_v1_0}EpsPrimaryPayerIdentifier"/>
 *         &lt;element ref="{http://enterprise.optum.com/schema/cim/api/finance/payables/provider/EpsPaymentMaintenanceService_v1_0}EpsSecondaryPayerReferenceIdentifier"/>
 *         &lt;element ref="{http://enterprise.optum.com/schema/cim/api/finance/payables/provider/EpsPaymentMaintenanceService_v1_0}PaymentTypeIndicator"/>
 *         &lt;element ref="{http://enterprise.optum.com/schema/cim/api/finance/payables/provider/EpsPaymentMaintenanceService_v1_0}PatientFirstName"/>
 *         &lt;element ref="{http://enterprise.optum.com/schema/cim/api/finance/payables/provider/EpsPaymentMaintenanceService_v1_0}PatientMiddleName" minOccurs="0"/>
 *         &lt;element ref="{http://enterprise.optum.com/schema/cim/api/finance/payables/provider/EpsPaymentMaintenanceService_v1_0}PatientLastName"/>
 *         &lt;element ref="{http://enterprise.optum.com/schema/cim/common/Identifier_v1_0}SubscriberIdentifier"/>
 *         &lt;element ref="{http://enterprise.optum.com/schema/cim/api/finance/payables/provider/EpsPaymentMaintenanceService_v1_0}PatientAccountNumber"/>
 *         &lt;element ref="{http://enterprise.optum.com/schema/cim/common/Identifier_v1_0}ClaimIdentifier"/>
 *         &lt;element ref="{http://enterprise.optum.com/schema/cim/common/Common_v1_0}ClaimAmount"/>
 *         &lt;element ref="{http://enterprise.optum.com/schema/cim/common/Common_v1_0}ClaimDate"/>
 *         &lt;element ref="{http://enterprise.optum.com/schema/cim/common/Common_v1_0}ClaimOrder"/>
 *         &lt;element ref="{http://enterprise.optum.com/schema/cim/api/finance/payables/provider/EpsPaymentMaintenanceService_v1_0}ClaimCountTotal"/>
 *         &lt;element ref="{http://enterprise.optum.com/schema/cim/api/finance/payables/provider/EpsPaymentMaintenanceService_v1_0}EpsClaimCount"/>
 *         &lt;element ref="{http://enterprise.optum.com/schema/cim/common/Identifier_v1_0}NationalProviderIdentifier"/>
 *         &lt;element ref="{http://enterprise.optum.com/schema/cim/api/finance/payables/provider/EpsPaymentMaintenanceService_v1_0}TraceNumber"/>
 *         &lt;element ref="{http://enterprise.optum.com/schema/cim/api/finance/payables/provider/EpsPaymentMaintenanceService_v1_0}ProxyIdentifier"/>
 *         &lt;element ref="{http://enterprise.optum.com/schema/cim/api/finance/payables/provider/EpsPaymentMaintenanceService_v1_0}PaymentStatusTypeDateTime"/>
 *         &lt;element ref="{http://enterprise.optum.com/schema/cim/api/finance/payables/provider/EpsPaymentMaintenanceService_v1_0}ArchiveIndicator"/>
 *         &lt;element ref="{http://enterprise.optum.com/schema/cim/common/Code_v1_0}PaymentReturnedReasonCode"/>
 *         &lt;element ref="{http://enterprise.optum.com/schema/cim/api/finance/payables/provider/EpsPaymentMaintenanceService_v1_0}EpsPaymentStatusCode"/>
 *         &lt;element ref="{http://enterprise.optum.com/schema/cim/api/finance/payables/provider/EpsPaymentMaintenanceService_v1_0}OriginalBpr01"/>
 *         &lt;element ref="{http://enterprise.optum.com/schema/cim/api/finance/payables/provider/EpsPaymentMaintenanceService_v1_0}OriginalBpr01s" maxOccurs="500000" minOccurs="0"/>
 *         &lt;element ref="{http://enterprise.optum.com/schema/cim/api/finance/payables/provider/EpsPaymentMaintenanceService_v1_0}EpsConsolidatedClaimPaymentDetails" maxOccurs="500000" minOccurs="0"/>
 *         &lt;element ref="{http://enterprise.optum.com/schema/cim/api/finance/payables/provider/EpsPaymentMaintenanceService_v1_0}EpsClaimPaymentResponses" maxOccurs="500000" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EpsConsolidatedClaimPaymentSummary", propOrder = {
    "schemaName",
    "displayConsolidatedPaymentNumber",
    "consolidatedPaymentNumber",
    "epsPrimaryPayerIdentifier",
    "epsSecondaryPayerReferenceIdentifier",
    "paymentTypeIndicator",
    "patientFirstName",
    "patientMiddleName",
    "patientLastName",
    "subscriberIdentifier",
    "patientAccountNumber",
    "claimIdentifier",
    "claimAmount",
    "claimDate",
    "claimOrder",
    "claimCountTotal",
    "epsClaimCount",
    "nationalProviderIdentifier",
    "traceNumber",
    "proxyIdentifier",
    "paymentStatusTypeDateTime",
    "archiveIndicator",
    "paymentReturnedReasonCode",
    "epsPaymentStatusCode",
    "originalBpr01",
    "originalBpr01S",
    "epsConsolidatedClaimPaymentDetails",
    "epsClaimPaymentResponses"
})
public class EpsConsolidatedClaimPaymentSummary
    extends Payment
{

    @XmlElement(name = "SchemaName", namespace = "http://enterprise.optum.com/schema/cim/common/Common_v1_0", required = true)
    protected String schemaName;
    @XmlElement(name = "DisplayConsolidatedPaymentNumber", namespace = "http://enterprise.optum.com/schema/cim/api/finance/payables/provider/EpsPaymentMaintenanceService_v1_0", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String displayConsolidatedPaymentNumber;
    @XmlElement(name = "ConsolidatedPaymentNumber", namespace = "http://enterprise.optum.com/schema/cim/api/finance/payables/provider/EpsPaymentMaintenanceService_v1_0", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String consolidatedPaymentNumber;
    @XmlElement(name = "EpsPrimaryPayerIdentifier", namespace = "http://enterprise.optum.com/schema/cim/api/finance/payables/provider/EpsPaymentMaintenanceService_v1_0", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String epsPrimaryPayerIdentifier;
    @XmlElement(name = "EpsSecondaryPayerReferenceIdentifier", namespace = "http://enterprise.optum.com/schema/cim/api/finance/payables/provider/EpsPaymentMaintenanceService_v1_0", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String epsSecondaryPayerReferenceIdentifier;
    @XmlElement(name = "PaymentTypeIndicator", namespace = "http://enterprise.optum.com/schema/cim/api/finance/payables/provider/EpsPaymentMaintenanceService_v1_0", required = true)
    protected String paymentTypeIndicator;
    @XmlElement(name = "PatientFirstName", namespace = "http://enterprise.optum.com/schema/cim/api/finance/payables/provider/EpsPaymentMaintenanceService_v1_0", required = true)
    protected String patientFirstName;
    @XmlElement(name = "PatientMiddleName", namespace = "http://enterprise.optum.com/schema/cim/api/finance/payables/provider/EpsPaymentMaintenanceService_v1_0")
    protected String patientMiddleName;
    @XmlElement(name = "PatientLastName", namespace = "http://enterprise.optum.com/schema/cim/api/finance/payables/provider/EpsPaymentMaintenanceService_v1_0", required = true)
    protected String patientLastName;
    @XmlElement(name = "SubscriberIdentifier", namespace = "http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String subscriberIdentifier;
    @XmlElement(name = "PatientAccountNumber", namespace = "http://enterprise.optum.com/schema/cim/api/finance/payables/provider/EpsPaymentMaintenanceService_v1_0", required = true)
    protected String patientAccountNumber;
    @XmlElement(name = "ClaimIdentifier", namespace = "http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", required = true)
    protected String claimIdentifier;
    @XmlElement(name = "ClaimAmount", namespace = "http://enterprise.optum.com/schema/cim/common/Common_v1_0", required = true)
    protected Currency claimAmount;
    @XmlElement(name = "ClaimDate", namespace = "http://enterprise.optum.com/schema/cim/common/Common_v1_0", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar claimDate;
    @XmlElement(name = "ClaimOrder", namespace = "http://enterprise.optum.com/schema/cim/common/Common_v1_0", required = true)
    protected BigInteger claimOrder;
    @XmlElement(name = "ClaimCountTotal", namespace = "http://enterprise.optum.com/schema/cim/api/finance/payables/provider/EpsPaymentMaintenanceService_v1_0")
    protected long claimCountTotal;
    @XmlElement(name = "EpsClaimCount", namespace = "http://enterprise.optum.com/schema/cim/api/finance/payables/provider/EpsPaymentMaintenanceService_v1_0")
    protected long epsClaimCount;
    @XmlElement(name = "NationalProviderIdentifier", namespace = "http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String nationalProviderIdentifier;
    @XmlElement(name = "TraceNumber", namespace = "http://enterprise.optum.com/schema/cim/api/finance/payables/provider/EpsPaymentMaintenanceService_v1_0", required = true)
    protected String traceNumber;
    @XmlElement(name = "ProxyIdentifier", namespace = "http://enterprise.optum.com/schema/cim/api/finance/payables/provider/EpsPaymentMaintenanceService_v1_0", required = true)
    protected String proxyIdentifier;
    @XmlElement(name = "PaymentStatusTypeDateTime", namespace = "http://enterprise.optum.com/schema/cim/api/finance/payables/provider/EpsPaymentMaintenanceService_v1_0", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar paymentStatusTypeDateTime;
    @XmlElement(name = "ArchiveIndicator", namespace = "http://enterprise.optum.com/schema/cim/api/finance/payables/provider/EpsPaymentMaintenanceService_v1_0", required = true)
    protected String archiveIndicator;
    @XmlElement(name = "PaymentReturnedReasonCode", namespace = "http://enterprise.optum.com/schema/cim/common/Code_v1_0", required = true)
    protected BaseCode paymentReturnedReasonCode;
    @XmlElement(name = "EpsPaymentStatusCode", namespace = "http://enterprise.optum.com/schema/cim/api/finance/payables/provider/EpsPaymentMaintenanceService_v1_0", required = true)
    protected EpsPaymentStatusCode epsPaymentStatusCode;
    @XmlElement(name = "OriginalBpr01", namespace = "http://enterprise.optum.com/schema/cim/api/finance/payables/provider/EpsPaymentMaintenanceService_v1_0", required = true)
    protected String originalBpr01;
    @XmlElement(name = "OriginalBpr01s", namespace = "http://enterprise.optum.com/schema/cim/api/finance/payables/provider/EpsPaymentMaintenanceService_v1_0")
    protected List<String> originalBpr01S;
    @XmlElement(name = "EpsConsolidatedClaimPaymentDetails", namespace = "http://enterprise.optum.com/schema/cim/api/finance/payables/provider/EpsPaymentMaintenanceService_v1_0")
    protected List<EpsConsolidatedClaimPaymentDetail> epsConsolidatedClaimPaymentDetails;
    @XmlElement(name = "EpsClaimPaymentResponses", namespace = "http://enterprise.optum.com/schema/cim/api/finance/payables/provider/EpsPaymentMaintenanceService_v1_0")
    protected List<EpsClaimPaymentResponse> epsClaimPaymentResponses;

    /**
     * Gets the value of the schemaName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSchemaName() {
        return schemaName;
    }

    /**
     * Sets the value of the schemaName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSchemaName(String value) {
        this.schemaName = value;
    }

    /**
     * Gets the value of the displayConsolidatedPaymentNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisplayConsolidatedPaymentNumber() {
        return displayConsolidatedPaymentNumber;
    }

    /**
     * Sets the value of the displayConsolidatedPaymentNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisplayConsolidatedPaymentNumber(String value) {
        this.displayConsolidatedPaymentNumber = value;
    }

    /**
     * Gets the value of the consolidatedPaymentNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConsolidatedPaymentNumber() {
        return consolidatedPaymentNumber;
    }

    /**
     * Sets the value of the consolidatedPaymentNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConsolidatedPaymentNumber(String value) {
        this.consolidatedPaymentNumber = value;
    }

    /**
     * Gets the value of the epsPrimaryPayerIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEpsPrimaryPayerIdentifier() {
        return epsPrimaryPayerIdentifier;
    }

    /**
     * Sets the value of the epsPrimaryPayerIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEpsPrimaryPayerIdentifier(String value) {
        this.epsPrimaryPayerIdentifier = value;
    }

    /**
     * Gets the value of the epsSecondaryPayerReferenceIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEpsSecondaryPayerReferenceIdentifier() {
        return epsSecondaryPayerReferenceIdentifier;
    }

    /**
     * Sets the value of the epsSecondaryPayerReferenceIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEpsSecondaryPayerReferenceIdentifier(String value) {
        this.epsSecondaryPayerReferenceIdentifier = value;
    }

    /**
     * Gets the value of the paymentTypeIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaymentTypeIndicator() {
        return paymentTypeIndicator;
    }

    /**
     * Sets the value of the paymentTypeIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymentTypeIndicator(String value) {
        this.paymentTypeIndicator = value;
    }

    /**
     * Gets the value of the patientFirstName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPatientFirstName() {
        return patientFirstName;
    }

    /**
     * Sets the value of the patientFirstName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPatientFirstName(String value) {
        this.patientFirstName = value;
    }

    /**
     * Gets the value of the patientMiddleName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPatientMiddleName() {
        return patientMiddleName;
    }

    /**
     * Sets the value of the patientMiddleName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPatientMiddleName(String value) {
        this.patientMiddleName = value;
    }

    /**
     * Gets the value of the patientLastName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPatientLastName() {
        return patientLastName;
    }

    /**
     * Sets the value of the patientLastName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPatientLastName(String value) {
        this.patientLastName = value;
    }

    /**
     * Gets the value of the subscriberIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubscriberIdentifier() {
        return subscriberIdentifier;
    }

    /**
     * Sets the value of the subscriberIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubscriberIdentifier(String value) {
        this.subscriberIdentifier = value;
    }

    /**
     * Gets the value of the patientAccountNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPatientAccountNumber() {
        return patientAccountNumber;
    }

    /**
     * Sets the value of the patientAccountNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPatientAccountNumber(String value) {
        this.patientAccountNumber = value;
    }

    /**
     * Gets the value of the claimIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClaimIdentifier() {
        return claimIdentifier;
    }

    /**
     * Sets the value of the claimIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClaimIdentifier(String value) {
        this.claimIdentifier = value;
    }

    /**
     * Gets the value of the claimAmount property.
     * 
     * @return
     *     possible object is
     *     {@link Currency }
     *     
     */
    public Currency getClaimAmount() {
        return claimAmount;
    }

    /**
     * Sets the value of the claimAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Currency }
     *     
     */
    public void setClaimAmount(Currency value) {
        this.claimAmount = value;
    }

    /**
     * Gets the value of the claimDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getClaimDate() {
        return claimDate;
    }

    /**
     * Sets the value of the claimDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setClaimDate(XMLGregorianCalendar value) {
        this.claimDate = value;
    }

    /**
     * Gets the value of the claimOrder property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getClaimOrder() {
        return claimOrder;
    }

    /**
     * Sets the value of the claimOrder property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setClaimOrder(BigInteger value) {
        this.claimOrder = value;
    }

    /**
     * 
     * 								Claim count at the Consolidated Payment level.
     * 							
     * 
     */
    public long getClaimCountTotal() {
        return claimCountTotal;
    }

    /**
     * Sets the value of the claimCountTotal property.
     * 
     */
    public void setClaimCountTotal(long value) {
        this.claimCountTotal = value;
    }

    /**
     * 
     * 								Claim count at the UnConsolidated Payment level.
     * 							
     * 
     */
    public long getEpsClaimCount() {
        return epsClaimCount;
    }

    /**
     * Sets the value of the epsClaimCount property.
     * 
     */
    public void setEpsClaimCount(long value) {
        this.epsClaimCount = value;
    }

    /**
     * Gets the value of the nationalProviderIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNationalProviderIdentifier() {
        return nationalProviderIdentifier;
    }

    /**
     * Sets the value of the nationalProviderIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNationalProviderIdentifier(String value) {
        this.nationalProviderIdentifier = value;
    }

    /**
     * Gets the value of the traceNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTraceNumber() {
        return traceNumber;
    }

    /**
     * Sets the value of the traceNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTraceNumber(String value) {
        this.traceNumber = value;
    }

    /**
     * Gets the value of the proxyIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProxyIdentifier() {
        return proxyIdentifier;
    }

    /**
     * Sets the value of the proxyIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProxyIdentifier(String value) {
        this.proxyIdentifier = value;
    }

    /**
     * Gets the value of the paymentStatusTypeDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPaymentStatusTypeDateTime() {
        return paymentStatusTypeDateTime;
    }

    /**
     * Sets the value of the paymentStatusTypeDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPaymentStatusTypeDateTime(XMLGregorianCalendar value) {
        this.paymentStatusTypeDateTime = value;
    }

    /**
     * Gets the value of the archiveIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArchiveIndicator() {
        return archiveIndicator;
    }

    /**
     * Sets the value of the archiveIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArchiveIndicator(String value) {
        this.archiveIndicator = value;
    }

    /**
     * Gets the value of the paymentReturnedReasonCode property.
     * 
     * @return
     *     possible object is
     *     {@link BaseCode }
     *     
     */
    public BaseCode getPaymentReturnedReasonCode() {
        return paymentReturnedReasonCode;
    }

    /**
     * Sets the value of the paymentReturnedReasonCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link BaseCode }
     *     
     */
    public void setPaymentReturnedReasonCode(BaseCode value) {
        this.paymentReturnedReasonCode = value;
    }

    /**
     * Gets the value of the epsPaymentStatusCode property.
     * 
     * @return
     *     possible object is
     *     {@link EpsPaymentStatusCode }
     *     
     */
    public EpsPaymentStatusCode getEpsPaymentStatusCode() {
        return epsPaymentStatusCode;
    }

    /**
     * Sets the value of the epsPaymentStatusCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link EpsPaymentStatusCode }
     *     
     */
    public void setEpsPaymentStatusCode(EpsPaymentStatusCode value) {
        this.epsPaymentStatusCode = value;
    }

    /**
     * Gets the value of the originalBpr01 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOriginalBpr01() {
        return originalBpr01;
    }

    /**
     * Sets the value of the originalBpr01 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOriginalBpr01(String value) {
        this.originalBpr01 = value;
    }

    /**
     * Gets the value of the originalBpr01S property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the originalBpr01S property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOriginalBpr01S().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getOriginalBpr01S() {
        if (originalBpr01S == null) {
            originalBpr01S = new ArrayList<String>();
        }
        return this.originalBpr01S;
    }

    /**
     * Gets the value of the epsConsolidatedClaimPaymentDetails property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the epsConsolidatedClaimPaymentDetails property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEpsConsolidatedClaimPaymentDetails().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EpsConsolidatedClaimPaymentDetail }
     * 
     * 
     */
    public List<EpsConsolidatedClaimPaymentDetail> getEpsConsolidatedClaimPaymentDetails() {
        if (epsConsolidatedClaimPaymentDetails == null) {
            epsConsolidatedClaimPaymentDetails = new ArrayList<EpsConsolidatedClaimPaymentDetail>();
        }
        return this.epsConsolidatedClaimPaymentDetails;
    }

    /**
     * Gets the value of the epsClaimPaymentResponses property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the epsClaimPaymentResponses property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEpsClaimPaymentResponses().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EpsClaimPaymentResponse }
     * 
     * 
     */
    public List<EpsClaimPaymentResponse> getEpsClaimPaymentResponses() {
        if (epsClaimPaymentResponses == null) {
            epsClaimPaymentResponses = new ArrayList<EpsClaimPaymentResponse>();
        }
        return this.epsClaimPaymentResponses;
    }

}
