//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.03 at 12:32:33 PM CDT 
//


package com.optum.enterprise.schema.cim.api.finance.payables.provider.paymentsservice_v1_0;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import com.optum.enterprise.schema.cim.api.finance.payables.provider.epspaymentmaintenanceservice_v1_0.ServiceData;
import com.optum.enterprise.schema.cim.common.common_v1_0.DateRange;
import com.optum.enterprise.schema.cim.common.service_v1_0.SearchByCriteriaRequest;


/**
 * 
 * 				
 * 				Request to search EPS payments, by specifying search criteria.				
 * 				
 * 			
 * 
 * <p>Java class for EpsPaymentsSearchRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EpsPaymentsSearchRequest">
 *   &lt;complexContent>
 *     &lt;extension base="{http://enterprise.optum.com/schema/cim/common/Service_v1_0}SearchByCriteriaRequest">
 *       &lt;sequence>
 *         &lt;element ref="{http://enterprise.optum.com/schema/cim/api/finance/payables/provider/EpsPaymentMaintenanceService_v1_0}ServiceData"/>
 *         &lt;element ref="{http://enterprise.optum.com/schema/cim/common/Identifier_v1_0}TaxIdentifierNumber"/>
 *         &lt;element ref="{http://enterprise.optum.com/schema/cim/api/finance/payables/provider/EpsPaymentMaintenanceService_v1_0}UserRole"/>
 *         &lt;element ref="{http://enterprise.optum.com/schema/cim/api/finance/payables/provider/EpsPaymentMaintenanceService_v1_0}subPayerId"/>
 *         &lt;choice>
 *           &lt;element ref="{http://enterprise.optum.com/schema/cim/common/Common_v1_0}PaymentMadeOnDateRange"/>
 *           &lt;element ref="{http://enterprise.optum.com/schema/cim/common/Common_v1_0}ClaimServiceDateRange"/>
 *         &lt;/choice>
 *         &lt;element ref="{http://enterprise.optum.com/schema/cim/api/finance/payables/provider/EpsPaymentMaintenanceService_v1_0}EpsSecondaryPayerReferenceIdentifiers" maxOccurs="500000" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EpsPaymentsSearchRequest", propOrder = {
    "serviceData",
    "taxIdentifierNumber",
    "userRole",
    "subPayerId",
    "paymentMadeOnDateRange",
    "claimServiceDateRange",
    "epsSecondaryPayerReferenceIdentifiers"
})
public class EpsPaymentsSearchRequest
    extends SearchByCriteriaRequest
{

    @XmlElement(name = "ServiceData", namespace = "http://enterprise.optum.com/schema/cim/api/finance/payables/provider/EpsPaymentMaintenanceService_v1_0", required = true)
    protected ServiceData serviceData;
    @XmlElement(name = "TaxIdentifierNumber", namespace = "http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String taxIdentifierNumber;
    @XmlElement(name = "UserRole", namespace = "http://enterprise.optum.com/schema/cim/api/finance/payables/provider/EpsPaymentMaintenanceService_v1_0", required = true)
    protected String userRole;
    @XmlElement(namespace = "http://enterprise.optum.com/schema/cim/api/finance/payables/provider/EpsPaymentMaintenanceService_v1_0", required = true)
    protected String subPayerId;
    @XmlElement(name = "PaymentMadeOnDateRange", namespace = "http://enterprise.optum.com/schema/cim/common/Common_v1_0")
    protected DateRange paymentMadeOnDateRange;
    @XmlElement(name = "ClaimServiceDateRange", namespace = "http://enterprise.optum.com/schema/cim/common/Common_v1_0")
    protected DateRange claimServiceDateRange;
    @XmlElement(name = "EpsSecondaryPayerReferenceIdentifiers", namespace = "http://enterprise.optum.com/schema/cim/api/finance/payables/provider/EpsPaymentMaintenanceService_v1_0")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected List<String> epsSecondaryPayerReferenceIdentifiers;

    /**
     * Gets the value of the serviceData property.
     * 
     * @return
     *     possible object is
     *     {@link ServiceData }
     *     
     */
    public ServiceData getServiceData() {
        return serviceData;
    }

    /**
     * Sets the value of the serviceData property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServiceData }
     *     
     */
    public void setServiceData(ServiceData value) {
        this.serviceData = value;
    }

    /**
     * Gets the value of the taxIdentifierNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxIdentifierNumber() {
        return taxIdentifierNumber;
    }

    /**
     * Sets the value of the taxIdentifierNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxIdentifierNumber(String value) {
        this.taxIdentifierNumber = value;
    }

    /**
     * Gets the value of the userRole property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserRole() {
        return userRole;
    }

    /**
     * Sets the value of the userRole property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserRole(String value) {
        this.userRole = value;
    }

    /**
     * Gets the value of the subPayerId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubPayerId() {
        return subPayerId;
    }

    /**
     * Sets the value of the subPayerId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubPayerId(String value) {
        this.subPayerId = value;
    }

    /**
     * Gets the value of the paymentMadeOnDateRange property.
     * 
     * @return
     *     possible object is
     *     {@link DateRange }
     *     
     */
    public DateRange getPaymentMadeOnDateRange() {
        return paymentMadeOnDateRange;
    }

    /**
     * Sets the value of the paymentMadeOnDateRange property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateRange }
     *     
     */
    public void setPaymentMadeOnDateRange(DateRange value) {
        this.paymentMadeOnDateRange = value;
    }

    /**
     * Gets the value of the claimServiceDateRange property.
     * 
     * @return
     *     possible object is
     *     {@link DateRange }
     *     
     */
    public DateRange getClaimServiceDateRange() {
        return claimServiceDateRange;
    }

    /**
     * Sets the value of the claimServiceDateRange property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateRange }
     *     
     */
    public void setClaimServiceDateRange(DateRange value) {
        this.claimServiceDateRange = value;
    }

    /**
     * Gets the value of the epsSecondaryPayerReferenceIdentifiers property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the epsSecondaryPayerReferenceIdentifiers property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEpsSecondaryPayerReferenceIdentifiers().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getEpsSecondaryPayerReferenceIdentifiers() {
        if (epsSecondaryPayerReferenceIdentifiers == null) {
            epsSecondaryPayerReferenceIdentifiers = new ArrayList<String>();
        }
        return this.epsSecondaryPayerReferenceIdentifiers;
    }

}
