//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.03 at 12:32:33 PM CDT 
//


package com.optum.enterprise.schema.cim.api.finance.payables.provider.paymentdetailservice_v1_0;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.optum.enterprise.schema.cim.api.finance.payables.provider.paymentdetailservice_v1_0 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _EpsPaymentDetail_QNAME = new QName("http://enterprise.optum.com/schema/cim/api/finance/payables/provider/PaymentDetailService_v1_0", "EpsPaymentDetail");
    private final static QName _EpsPaymentDetails_QNAME = new QName("http://enterprise.optum.com/schema/cim/api/finance/payables/provider/PaymentDetailService_v1_0", "EpsPaymentDetails");
    private final static QName _EpsPaymentDetailRequest_QNAME = new QName("http://enterprise.optum.com/schema/cim/api/finance/payables/provider/PaymentDetailService_v1_0", "EpsPaymentDetailRequest");
    private final static QName _EpsPaymentDetailResponse_QNAME = new QName("http://enterprise.optum.com/schema/cim/api/finance/payables/provider/PaymentDetailService_v1_0", "EpsPaymentDetailResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.optum.enterprise.schema.cim.api.finance.payables.provider.paymentdetailservice_v1_0
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link EpsPaymentDetailRequest }
     * 
     */
    public EpsPaymentDetailRequest createEpsPaymentDetailRequest() {
        return new EpsPaymentDetailRequest();
    }

    /**
     * Create an instance of {@link EpsPaymentDetail }
     * 
     */
    public EpsPaymentDetail createEpsPaymentDetail() {
        return new EpsPaymentDetail();
    }

    /**
     * Create an instance of {@link EpsPaymentDetailResponse }
     * 
     */
    public EpsPaymentDetailResponse createEpsPaymentDetailResponse() {
        return new EpsPaymentDetailResponse();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EpsPaymentDetail }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://enterprise.optum.com/schema/cim/api/finance/payables/provider/PaymentDetailService_v1_0", name = "EpsPaymentDetail")
    public JAXBElement<EpsPaymentDetail> createEpsPaymentDetail(EpsPaymentDetail value) {
        return new JAXBElement<EpsPaymentDetail>(_EpsPaymentDetail_QNAME, EpsPaymentDetail.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EpsPaymentDetail }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://enterprise.optum.com/schema/cim/api/finance/payables/provider/PaymentDetailService_v1_0", name = "EpsPaymentDetails")
    public JAXBElement<EpsPaymentDetail> createEpsPaymentDetails(EpsPaymentDetail value) {
        return new JAXBElement<EpsPaymentDetail>(_EpsPaymentDetails_QNAME, EpsPaymentDetail.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EpsPaymentDetailRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://enterprise.optum.com/schema/cim/api/finance/payables/provider/PaymentDetailService_v1_0", name = "EpsPaymentDetailRequest")
    public JAXBElement<EpsPaymentDetailRequest> createEpsPaymentDetailRequest(EpsPaymentDetailRequest value) {
        return new JAXBElement<EpsPaymentDetailRequest>(_EpsPaymentDetailRequest_QNAME, EpsPaymentDetailRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EpsPaymentDetailResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://enterprise.optum.com/schema/cim/api/finance/payables/provider/PaymentDetailService_v1_0", name = "EpsPaymentDetailResponse")
    public JAXBElement<EpsPaymentDetailResponse> createEpsPaymentDetailResponse(EpsPaymentDetailResponse value) {
        return new JAXBElement<EpsPaymentDetailResponse>(_EpsPaymentDetailResponse_QNAME, EpsPaymentDetailResponse.class, null, value);
    }

}
