//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.03 at 12:32:33 PM CDT 
//


package com.optum.enterprise.schema.cim.api.finance.payables.provider.edi835contentservice_v1_0;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.optum.enterprise.schema.cim.api.finance.payables.provider.edi835contentservice_v1_0 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _EpsEdi835ContentResponse_QNAME = new QName("http://enterprise.optum.com/schema/cim/api/finance/payables/provider/Edi835ContentService_v1_0", "EpsEdi835ContentResponse");
    private final static QName _EpsEdi835ContentRequest_QNAME = new QName("http://enterprise.optum.com/schema/cim/api/finance/payables/provider/Edi835ContentService_v1_0", "EpsEdi835ContentRequest");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.optum.enterprise.schema.cim.api.finance.payables.provider.edi835contentservice_v1_0
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link EpsEdi835ContentResponse }
     * 
     */
    public EpsEdi835ContentResponse createEpsEdi835ContentResponse() {
        return new EpsEdi835ContentResponse();
    }

    /**
     * Create an instance of {@link EpsEdi835ContentRequest }
     * 
     */
    public EpsEdi835ContentRequest createEpsEdi835ContentRequest() {
        return new EpsEdi835ContentRequest();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EpsEdi835ContentResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://enterprise.optum.com/schema/cim/api/finance/payables/provider/Edi835ContentService_v1_0", name = "EpsEdi835ContentResponse")
    public JAXBElement<EpsEdi835ContentResponse> createEpsEdi835ContentResponse(EpsEdi835ContentResponse value) {
        return new JAXBElement<EpsEdi835ContentResponse>(_EpsEdi835ContentResponse_QNAME, EpsEdi835ContentResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EpsEdi835ContentRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://enterprise.optum.com/schema/cim/api/finance/payables/provider/Edi835ContentService_v1_0", name = "EpsEdi835ContentRequest")
    public JAXBElement<EpsEdi835ContentRequest> createEpsEdi835ContentRequest(EpsEdi835ContentRequest value) {
        return new JAXBElement<EpsEdi835ContentRequest>(_EpsEdi835ContentRequest_QNAME, EpsEdi835ContentRequest.class, null, value);
    }

}
