//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.03 at 12:32:33 PM CDT 
//


package com.optum.enterprise.schema.cim.common.code_v1_0;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import com.optum.enterprise.schema.cim.api.finance.payables.provider.epspaymentmaintenanceservice_v1_0.EpsPaymentStatusCode;
import com.optum.enterprise.schema.cim.api.finance.payables.provider.epspaymentmaintenanceservice_v1_0.EpsReferenceIdentifierQualifierCode;


/**
 * 
 * 				Code types specifying Code, Name, Description,
 * 				Display Order Number and Active indicator etc. The code is not
 * 				enumerated, and
 * 				thus leaves more flexibility for service
 * 				provider, at the expense of no visibility for service consumer,
 * 				as the codes are not enumerated.
 * 			
 * 
 * <p>Java class for BaseCode complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BaseCode">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;group ref="{http://enterprise.optum.com/schema/cim/common/Code_v1_0}BaseCodeGroup"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BaseCode", propOrder = {
    "code",
    "name",
    "description",
    "displayOrder",
    "active",
    "effectiveDate",
    "endDate"
})
@XmlSeeAlso({
    SpecialtyCode.class,
    IntegrationSystemCode.class,
    EventSubTypeCode.class,
    MerchantClassificationCode.class,
    AccountStatusCode.class,
    TierCode.class,
    BillingGroupStatusCode.class,
    CoordinationOfBenefitsCode.class,
    BillingCreditTypeCode.class,
    DiagnosisCode.class,
    PlanVariationReasonCode.class,
    MedicareStatusCode.class,
    SurgicalProcedureCode.class,
    CoordinationOfBenefitsMethodCode.class,
    ContractProviderParticipationCode.class,
    MedicalServiceTypeCode.class,
    MedicalProcedureCode.class,
    ClaimReasonCode.class,
    EpsPaymentStatusCode.class,
    EpsReferenceIdentifierQualifierCode.class,
    ClaimPaymentAdjustmentReasonCode.class,
    MedicalProductCoverageTypeCode.class,
    ProductTypeCode.class,
    PlaceOfServiceCode.class,
    MedicalProductBusinessTypeCode.class,
    HipaaStatusCategoryCode.class,
    MedicarePlanCode.class,
    AffordableCareActMtlLevelCode.class,
    HipaaStatusCode.class,
    MedicareActionDenialCode.class,
    ProcessingPlanCode.class,
    ProductOfferingFamilyCode.class,
    PlanStatusCode.class,
    CPTProcedureCode.class,
    MedicalProductCdhpTaxRegulatoryCode.class,
    LimitationAccumulatorCode.class,
    AdmissionCode.class,
    RatingAreaCode.class,
    MedicalProductCoverageRegulatoryCode.class,
    MedicalProductDeliveryMethodCode.class,
    AffordableCareActQhpSimilarCode.class,
    TaxIdentifierCode.class,
    AgentCommissionCode.class,
    PayerResponsibilitySequenceNumberCode.class,
    SalesChannelCode.class
})
public class BaseCode {

    @XmlElement(name = "Code", required = true)
    protected String code;
    @XmlElement(name = "Name", namespace = "http://enterprise.optum.com/schema/cim/common/Common_v1_0")
    protected String name;
    @XmlElement(name = "Description", namespace = "http://enterprise.optum.com/schema/cim/common/Common_v1_0")
    protected String description;
    @XmlElement(name = "DisplayOrder", namespace = "http://enterprise.optum.com/schema/cim/common/Common_v1_0")
    @XmlSchemaType(name = "unsignedShort")
    protected Integer displayOrder;
    @XmlElement(name = "Active", namespace = "http://enterprise.optum.com/schema/cim/common/Common_v1_0")
    protected Boolean active;
    @XmlElement(name = "EffectiveDate", namespace = "http://enterprise.optum.com/schema/cim/common/Common_v1_0")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar effectiveDate;
    @XmlElement(name = "EndDate", namespace = "http://enterprise.optum.com/schema/cim/common/Common_v1_0")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar endDate;

    /**
     * Gets the value of the code property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCode() {
        return code;
    }

    /**
     * Sets the value of the code property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCode(String value) {
        this.code = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the displayOrder property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getDisplayOrder() {
        return displayOrder;
    }

    /**
     * Sets the value of the displayOrder property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setDisplayOrder(Integer value) {
        this.displayOrder = value;
    }

    /**
     * Gets the value of the active property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isActive() {
        return active;
    }

    /**
     * Sets the value of the active property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setActive(Boolean value) {
        this.active = value;
    }

    /**
     * Gets the value of the effectiveDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEffectiveDate() {
        return effectiveDate;
    }

    /**
     * Sets the value of the effectiveDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEffectiveDate(XMLGregorianCalendar value) {
        this.effectiveDate = value;
    }

    /**
     * Gets the value of the endDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEndDate() {
        return endDate;
    }

    /**
     * Sets the value of the endDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEndDate(XMLGregorianCalendar value) {
        this.endDate = value;
    }

}
