//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.03 at 12:32:33 PM CDT 
//


package com.optum.enterprise.schema.cim.common.code_v1_0;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MaintenanceReasonCodeEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="MaintenanceReasonCodeEnum">
 *   &lt;restriction base="{http://enterprise.optum.com/schema/cim/common/Code_v1_0}CodeType">
 *     &lt;enumeration value="TERMINATION_OF_BENEFITS"/>
 *     &lt;enumeration value="INFO_ONLY"/>
 *     &lt;enumeration value="IDENTIFICATION_DATA_CHANGED"/>
 *     &lt;enumeration value="DECLINED"/>
 *     &lt;enumeration value="NON_PAYMENT"/>
 *     &lt;enumeration value="FRAUD"/>
 *     &lt;enumeration value="TRIAL_PERIOD_END"/>
 *     &lt;enumeration value="RE_ENROLLMENT"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "MaintenanceReasonCodeEnum")
@XmlEnum
public enum MaintenanceReasonCodeEnum {


    /**
     * 
     * 						Termination of Benefits
     * 					
     * 
     */
    TERMINATION_OF_BENEFITS,

    /**
     * 
     * 						Informational only purposes
     * 					
     * 
     */
    INFO_ONLY,

    /**
     * 
     * 						Change in Identifying Data Elements
     * 					
     * 
     */
    IDENTIFICATION_DATA_CHANGED,

    /**
     * 
     * 						Declined
     * 					
     * 
     */
    DECLINED,

    /**
     * 
     * 						Non Payment
     * 					
     * 
     */
    NON_PAYMENT,

    /**
     * 
     * 						Fraud
     * 					
     * 
     */
    FRAUD,

    /**
     * 
     * 						Termination dute to trial period ending.
     * 					
     * 
     */
    TRIAL_PERIOD_END,

    /**
     * 
     * 						Re-enrolling after cancellation/termination.
     * 					
     * 
     */
    RE_ENROLLMENT;

    public String value() {
        return name();
    }

    public static MaintenanceReasonCodeEnum fromValue(String v) {
        return valueOf(v);
    }

}
