//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.03 at 12:32:33 PM CDT 
//


package com.optum.enterprise.schema.cim.common.code_v1_0;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				MASOOD: Explicit code enumerations. I tend to
 * 				enumerate when the types are known. This also helps service
 * 				consumers in a SOA environment. On the other hand leaving this
 * 				element as BaseCode gives service providers/developers easier
 * 				way to maintain code tables in the DB for code types, instead of
 * 				XSD
 * 				defined enums. BaseCode provides this capability.
 * 
 * 				However, I argue
 * 				that service providers can translate the XSD
 * 				enums to their
 * 				respective code types. This way the consumers
 * 				know what to send in
 * 				code types as it is enumerated in the XSD.
 * 			
 * 
 * <p>Java class for MaintenanceTypeCode complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MaintenanceTypeCode">
 *   &lt;complexContent>
 *     &lt;extension base="{http://enterprise.optum.com/schema/cim/common/Code_v1_0}AbstractEnumeratedCode">
 *       &lt;sequence>
 *         &lt;element name="Code" type="{http://enterprise.optum.com/schema/cim/common/Code_v1_0}MaintenanceTypeCodeEnum"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MaintenanceTypeCode", propOrder = {
    "code"
})
public class MaintenanceTypeCode
    extends AbstractEnumeratedCode
{

    @XmlElement(name = "Code", required = true)
    protected MaintenanceTypeCodeEnum code;

    /**
     * Gets the value of the code property.
     * 
     * @return
     *     possible object is
     *     {@link MaintenanceTypeCodeEnum }
     *     
     */
    public MaintenanceTypeCodeEnum getCode() {
        return code;
    }

    /**
     * Sets the value of the code property.
     * 
     * @param value
     *     allowed object is
     *     {@link MaintenanceTypeCodeEnum }
     *     
     */
    public void setCode(MaintenanceTypeCodeEnum value) {
        this.code = value;
    }

}
