//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.03 at 12:32:33 PM CDT 
//


package com.optum.enterprise.schema.cim.common.code_v1_0;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MaritalStatusCodeEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="MaritalStatusCodeEnum">
 *   &lt;restriction base="{http://enterprise.optum.com/schema/cim/common/Code_v1_0}CodeType">
 *     &lt;enumeration value="SINGLE"/>
 *     &lt;enumeration value="MARRIED"/>
 *     &lt;enumeration value="WIDOWED"/>
 *     &lt;enumeration value="DIVORCED"/>
 *     &lt;enumeration value="REGISTERED_DOMESTIC_PARTNER"/>
 *     &lt;enumeration value="SEPARATED"/>
 *     &lt;enumeration value="LEGALLY_SEPARATED"/>
 *     &lt;enumeration value="UNKNOWN"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "MaritalStatusCodeEnum")
@XmlEnum
public enum MaritalStatusCodeEnum {

    SINGLE,
    MARRIED,
    WIDOWED,
    DIVORCED,
    REGISTERED_DOMESTIC_PARTNER,
    SEPARATED,
    LEGALLY_SEPARATED,
    UNKNOWN;

    public String value() {
        return name();
    }

    public static MaritalStatusCodeEnum fromValue(String v) {
        return valueOf(v);
    }

}
