//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.03 at 12:32:33 PM CDT 
//


package com.optum.enterprise.schema.cim.common.code_v1_0;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ProcessingStatusCodeEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ProcessingStatusCodeEnum">
 *   &lt;restriction base="{http://enterprise.optum.com/schema/cim/common/Code_v1_0}CodeType">
 *     &lt;enumeration value="INITIATED"/>
 *     &lt;enumeration value="VALIDATED"/>
 *     &lt;enumeration value="IN_PROCESS"/>
 *     &lt;enumeration value="COMPLETED"/>
 *     &lt;enumeration value="FAILED"/>
 *     &lt;enumeration value="ADDITIONAL_INFORMATION_REQUIRED"/>
 *     &lt;enumeration value="REPROCESSED"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ProcessingStatusCodeEnum")
@XmlEnum
public enum ProcessingStatusCodeEnum {


    /**
     * 
     * 						Request received
     * 					
     * 
     */
    INITIATED,

    /**
     * 
     * 						Syntactically validated
     * 					
     * 
     */
    VALIDATED,

    /**
     * 
     * 						Synchronous Response sent. Asynchoronous back-end
     * 						processing on-going
     * 					
     * 
     */
    IN_PROCESS,

    /**
     * 
     * 						All responses sent. All back-end processing
     * 						completed
     * 					
     * 
     */
    COMPLETED,

    /**
     * 
     * 						Consumer needs to take action, possibly resend
     * 					
     * 
     */
    FAILED,

    /**
     * 
     * 						Cannot start processing, until more information
     * 						received
     * 					
     * 
     */
    ADDITIONAL_INFORMATION_REQUIRED,

    /**
     * 
     * 						Processed one, and then processed again.
     * 					
     * 
     */
    REPROCESSED;

    public String value() {
        return name();
    }

    public static ProcessingStatusCodeEnum fromValue(String v) {
        return valueOf(v);
    }

}
