//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.03 at 12:32:33 PM CDT 
//


package com.optum.enterprise.schema.cim.common.code_v1_0;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SystemCodeEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="SystemCodeEnum">
 *   &lt;restriction base="{http://enterprise.optum.com/schema/cim/common/Code_v1_0}CodeType">
 *     &lt;enumeration value="CIRRUS"/>
 *     &lt;enumeration value="TOPS"/>
 *     &lt;enumeration value="BRMS"/>
 *     &lt;enumeration value="EPS"/>
 *     &lt;enumeration value="TBD"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "SystemCodeEnum")
@XmlEnum
public enum SystemCodeEnum {


    /**
     * 
     * 						
     * 						MASOOD TBD: What is CIRRUS?
     * 						
     * 					
     * 
     */
    CIRRUS,

    /**
     * 
     * 						
     * 						MASOOD TBD: What is TOPS?
     * 						
     * 					
     * 
     */
    TOPS,

    /**
     * 
     * 						
     * 						MASOOD TBD: What is BRMS?
     * 						
     * 					
     * 
     */
    BRMS,

    /**
     * 
     * 						
     * 						MASOOD TBD: What is EPS?
     * 						
     * 					
     * 
     */
    EPS,

    /**
     * 
     * 						
     * 						MASOOD TBD: Add names here everytime you hear some 
     * 						esoteric acronym.
     * 						
     * 					
     * 
     */
    TBD;

    public String value() {
        return name();
    }

    public static SystemCodeEnum fromValue(String v) {
        return valueOf(v);
    }

}
