//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.03 at 12:32:33 PM CDT 
//


package com.optum.enterprise.schema.cim.common.code_v1_0;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TimezoneCodeEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TimezoneCodeEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}normalizedString">
 *     &lt;enumeration value="CANADA_CENTRAL"/>
 *     &lt;enumeration value="CANADA_EASTERN"/>
 *     &lt;enumeration value="CANADA_MOUNTAIN"/>
 *     &lt;enumeration value="CANADA_NEWFOUNDLAND"/>
 *     &lt;enumeration value="CANADA_PACIFIC"/>
 *     &lt;enumeration value="CANADA_SASKATCHEWAN"/>
 *     &lt;enumeration value="CANADA_YUKON"/>
 *     &lt;enumeration value="US_ALASKA"/>
 *     &lt;enumeration value="US_CENTRAL"/>
 *     &lt;enumeration value="US_EASTERN"/>
 *     &lt;enumeration value="US_HAWAII"/>
 *     &lt;enumeration value="US_MOUNTAIN"/>
 *     &lt;enumeration value="US_PACIFIC"/>
 *     &lt;enumeration value="US_SAMOA"/>
 *     &lt;enumeration value="US_ZULU"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "TimezoneCodeEnum")
@XmlEnum
public enum TimezoneCodeEnum {


    /**
     * Canada/Central
     * 
     */
    CANADA_CENTRAL,

    /**
     * Canada/Eastern
     * 
     */
    CANADA_EASTERN,

    /**
     * Canada/Mountain
     * 
     */
    CANADA_MOUNTAIN,

    /**
     * Canada/Newfoundland
     * 
     */
    CANADA_NEWFOUNDLAND,

    /**
     * Canada/Pacific
     * 
     */
    CANADA_PACIFIC,

    /**
     * Canada/Saskatchewan
     * 
     */
    CANADA_SASKATCHEWAN,

    /**
     * Canada/Yukon
     * 
     */
    CANADA_YUKON,

    /**
     * US/Alaska
     * 
     */
    US_ALASKA,

    /**
     * US/Central
     * 
     */
    US_CENTRAL,

    /**
     * US/Eastern
     * 
     */
    US_EASTERN,

    /**
     * US/Hawaii
     * 
     */
    US_HAWAII,

    /**
     * US/Mountain
     * 
     */
    US_MOUNTAIN,

    /**
     * US/Pacific
     * 
     */
    US_PACIFIC,

    /**
     * US/Samoa
     * 
     */
    US_SAMOA,

    /**
     * US/Zulu
     * 
     */
    US_ZULU;

    public String value() {
        return name();
    }

    public static TimezoneCodeEnum fromValue(String v) {
        return valueOf(v);
    }

}
