//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.03 at 12:32:33 PM CDT 
//


package com.optum.enterprise.schema.cim.common.identifier_v1_0;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.optum.enterprise.schema.cim.common.identifier_v1_0 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _UniqueIdentifier_QNAME = new QName("http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", "UniqueIdentifier");
    private final static QName _PayerSecondaryIdentifier_QNAME = new QName("http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", "PayerSecondaryIdentifier");
    private final static QName _InvoiceNumber_QNAME = new QName("http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", "InvoiceNumber");
    private final static QName _EventRecipientIdentifier_QNAME = new QName("http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", "EventRecipientIdentifier");
    private final static QName _CustomerIdentifier_QNAME = new QName("http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", "CustomerIdentifier");
    private final static QName _BillingGroupIdentifier_QNAME = new QName("http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", "BillingGroupIdentifier");
    private final static QName _OptumAssignedAgencyCodeIdentifier_QNAME = new QName("http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", "OptumAssignedAgencyCodeIdentifier");
    private final static QName _EnrolleeNumber_QNAME = new QName("http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", "EnrolleeNumber");
    private final static QName _OrderIdentifier_QNAME = new QName("http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", "OrderIdentifier");
    private final static QName _PolicyNumbers_QNAME = new QName("http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", "PolicyNumbers");
    private final static QName _RequestIdentifier_QNAME = new QName("http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", "RequestIdentifier");
    private final static QName _SocialSecurityNumberFormatted_QNAME = new QName("http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", "SocialSecurityNumberFormatted");
    private final static QName _NationalProviderIdentifier_QNAME = new QName("http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", "NationalProviderIdentifier");
    private final static QName _ReturnedReoriginatedIdentifier_QNAME = new QName("http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", "ReturnedReoriginatedIdentifier");
    private final static QName _EventIdentifier_QNAME = new QName("http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", "EventIdentifier");
    private final static QName _OperatorIdentifier_QNAME = new QName("http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", "OperatorIdentifier");
    private final static QName _PersonIdentifier_QNAME = new QName("http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", "PersonIdentifier");
    private final static QName _SocialSecurityNumber_QNAME = new QName("http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", "SocialSecurityNumber");
    private final static QName _MedicareIdentifier_QNAME = new QName("http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", "MedicareIdentifier");
    private final static QName _AccountNumber_QNAME = new QName("http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", "AccountNumber");
    private final static QName _NetworkIdentifier_QNAME = new QName("http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", "NetworkIdentifier");
    private final static QName _NachaResponseIdentifier_QNAME = new QName("http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", "NachaResponseIdentifier");
    private final static QName _NoteIdentifier_QNAME = new QName("http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", "NoteIdentifier");
    private final static QName _BusinessIdentifier_QNAME = new QName("http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", "BusinessIdentifier");
    private final static QName _TaxIdentifierNumber_QNAME = new QName("http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", "TaxIdentifierNumber");
    private final static QName _AudioIdentifier_QNAME = new QName("http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", "AudioIdentifier");
    private final static QName _PayerPrimaryIdentifier_QNAME = new QName("http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", "PayerPrimaryIdentifier");
    private final static QName _LegacyIdentifier_QNAME = new QName("http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", "LegacyIdentifier");
    private final static QName _ImageIdentifier_QNAME = new QName("http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", "ImageIdentifier");
    private final static QName _UniqueUniversalIdentifier_QNAME = new QName("http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", "UniqueUniversalIdentifier");
    private final static QName _OptumAssignedGroupIdentifier_QNAME = new QName("http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", "OptumAssignedGroupIdentifier");
    private final static QName _OptumAssignedSubGroupIdentifier_QNAME = new QName("http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", "OptumAssignedSubGroupIdentifier");
    private final static QName _MedicaidIdentifier_QNAME = new QName("http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", "MedicaidIdentifier");
    private final static QName _SenderAssignedSubscriberIdentifier_QNAME = new QName("http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", "SenderAssignedSubscriberIdentifier");
    private final static QName _VideoIdentifier_QNAME = new QName("http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", "VideoIdentifier");
    private final static QName _MembershipOwnerIdentifier_QNAME = new QName("http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", "MembershipOwnerIdentifier");
    private final static QName _TextIdentifier_QNAME = new QName("http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", "TextIdentifier");
    private final static QName _PaymentMethodIdentifier_QNAME = new QName("http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", "PaymentMethodIdentifier");
    private final static QName _OptumAssignedMemberIdentifier_QNAME = new QName("http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", "OptumAssignedMemberIdentifier");
    private final static QName _CustomerNotificationIdentifier_QNAME = new QName("http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", "CustomerNotificationIdentifier");
    private final static QName _UniqueIdentifiers_QNAME = new QName("http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", "UniqueIdentifiers");
    private final static QName _ConsolidatedPaymentDetailIdentifier_QNAME = new QName("http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", "ConsolidatedPaymentDetailIdentifier");
    private final static QName _SenderAssignedGroupIdentifier_QNAME = new QName("http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", "SenderAssignedGroupIdentifier");
    private final static QName _PolicyNumber_QNAME = new QName("http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", "PolicyNumber");
    private final static QName _ClientIdentifier_QNAME = new QName("http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", "ClientIdentifier");
    private final static QName _NewBankRoutingNumber_QNAME = new QName("http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", "NewBankRoutingNumber");
    private final static QName _BenefitIdentifier_QNAME = new QName("http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", "BenefitIdentifier");
    private final static QName _BankAccountNumber_QNAME = new QName("http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", "BankAccountNumber");
    private final static QName _CostCenterIdentifier_QNAME = new QName("http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", "CostCenterIdentifier");
    private final static QName _ClientHealthCoverageIdentifier_QNAME = new QName("http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", "ClientHealthCoverageIdentifier");
    private final static QName _HealthPlanOwnerIdentifier_QNAME = new QName("http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", "HealthPlanOwnerIdentifier");
    private final static QName _OptumAssignedPlanIdentifier_QNAME = new QName("http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", "OptumAssignedPlanIdentifier");
    private final static QName _TransactionIdentifier_QNAME = new QName("http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", "TransactionIdentifier");
    private final static QName _OptumAssignedAgentIdentifier_QNAME = new QName("http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", "OptumAssignedAgentIdentifier");
    private final static QName _SenderAssignedMemberIdentifier_QNAME = new QName("http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", "SenderAssignedMemberIdentifier");
    private final static QName _HealthCardIdentifier_QNAME = new QName("http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", "HealthCardIdentifier");
    private final static QName _MemberIdentifier_QNAME = new QName("http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", "MemberIdentifier");
    private final static QName _SubscriberIdentifier_QNAME = new QName("http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", "SubscriberIdentifier");
    private final static QName _PaymentIdentifier_QNAME = new QName("http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", "PaymentIdentifier");
    private final static QName _ProductIdentifier_QNAME = new QName("http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", "ProductIdentifier");
    private final static QName _SenderAssignedPlanIdentifier_QNAME = new QName("http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", "SenderAssignedPlanIdentifier");
    private final static QName _SocialSecurityNumberEncrypted_QNAME = new QName("http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", "SocialSecurityNumberEncrypted");
    private final static QName _PackageIdentifier_QNAME = new QName("http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", "PackageIdentifier");
    private final static QName _CoordinationOfBenefitsTypeIdentifier_QNAME = new QName("http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", "CoordinationOfBenefitsTypeIdentifier");
    private final static QName _ClaimIdentifier_QNAME = new QName("http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", "ClaimIdentifier");
    private final static QName _BillingAccountIdentifier_QNAME = new QName("http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", "BillingAccountIdentifier");
    private final static QName _PrescriptionNumber_QNAME = new QName("http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", "PrescriptionNumber");
    private final static QName _PayerIdentifier_QNAME = new QName("http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", "PayerIdentifier");
    private final static QName _HomePlanIdentifier_QNAME = new QName("http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", "HomePlanIdentifier");
    private final static QName _PlanIdentifier_QNAME = new QName("http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", "PlanIdentifier");
    private final static QName _PatientIdentifier_QNAME = new QName("http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", "PatientIdentifier");
    private final static QName _ProviderEnrollmentIdentifier_QNAME = new QName("http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", "ProviderEnrollmentIdentifier");
    private final static QName _BankRoutingNumber_QNAME = new QName("http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", "BankRoutingNumber");
    private final static QName _BasePlanIdentifier_QNAME = new QName("http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", "BasePlanIdentifier");
    private final static QName _AgentIdentifier_QNAME = new QName("http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", "AgentIdentifier");
    private final static QName _NewBankAccountNumber_QNAME = new QName("http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", "NewBankAccountNumber");
    private final static QName _ConfirmationNumber_QNAME = new QName("http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", "ConfirmationNumber");
    private final static QName _CorrelationIdentifier_QNAME = new QName("http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", "CorrelationIdentifier");
    private final static QName _UserIdentifier_QNAME = new QName("http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", "UserIdentifier");
    private final static QName _RecipientConfigurationIdentifier_QNAME = new QName("http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", "RecipientConfigurationIdentifier");
    private final static QName _GroupIdentifier_QNAME = new QName("http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", "GroupIdentifier");
    private final static QName _BillingIdentifier_QNAME = new QName("http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", "BillingIdentifier");
    private final static QName _OptumAssignedSubscriberIdentifier_QNAME = new QName("http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", "OptumAssignedSubscriberIdentifier");
    private final static QName _BillingGroupIdentifiers_QNAME = new QName("http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", "BillingGroupIdentifiers");
    private final static QName _CreditCardBillingIdentifier_QNAME = new QName("http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", "CreditCardBillingIdentifier");
    private final static QName _SubGroupIdentifier_QNAME = new QName("http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", "SubGroupIdentifier");
    private final static QName _Identifier_QNAME = new QName("http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", "Identifier");
    private final static QName _ProviderIdentifier_QNAME = new QName("http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", "ProviderIdentifier");
    private final static QName _CheckNumber_QNAME = new QName("http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", "CheckNumber");
    private final static QName _SenderAssignedPolicyIdentifier_QNAME = new QName("http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", "SenderAssignedPolicyIdentifier");
    private final static QName _EntityIdentifier_QNAME = new QName("http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", "EntityIdentifier");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.optum.enterprise.schema.cim.common.identifier_v1_0
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ClientHealthCoverageIdentifier }
     * 
     */
    public ClientHealthCoverageIdentifier createClientHealthCoverageIdentifier() {
        return new ClientHealthCoverageIdentifier();
    }

    /**
     * Create an instance of {@link UniqueIdentifier }
     * 
     */
    public UniqueIdentifier createUniqueIdentifier() {
        return new UniqueIdentifier();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UniqueIdentifier }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", name = "UniqueIdentifier")
    public JAXBElement<UniqueIdentifier> createUniqueIdentifier(UniqueIdentifier value) {
        return new JAXBElement<UniqueIdentifier>(_UniqueIdentifier_QNAME, UniqueIdentifier.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", name = "PayerSecondaryIdentifier")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    public JAXBElement<String> createPayerSecondaryIdentifier(String value) {
        return new JAXBElement<String>(_PayerSecondaryIdentifier_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", name = "InvoiceNumber")
    public JAXBElement<Long> createInvoiceNumber(Long value) {
        return new JAXBElement<Long>(_InvoiceNumber_QNAME, Long.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", name = "EventRecipientIdentifier")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    public JAXBElement<String> createEventRecipientIdentifier(String value) {
        return new JAXBElement<String>(_EventRecipientIdentifier_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", name = "CustomerIdentifier")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    public JAXBElement<String> createCustomerIdentifier(String value) {
        return new JAXBElement<String>(_CustomerIdentifier_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", name = "BillingGroupIdentifier")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    public JAXBElement<String> createBillingGroupIdentifier(String value) {
        return new JAXBElement<String>(_BillingGroupIdentifier_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", name = "OptumAssignedAgencyCodeIdentifier")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    public JAXBElement<String> createOptumAssignedAgencyCodeIdentifier(String value) {
        return new JAXBElement<String>(_OptumAssignedAgencyCodeIdentifier_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", name = "EnrolleeNumber")
    public JAXBElement<Long> createEnrolleeNumber(Long value) {
        return new JAXBElement<Long>(_EnrolleeNumber_QNAME, Long.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", name = "OrderIdentifier")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    public JAXBElement<String> createOrderIdentifier(String value) {
        return new JAXBElement<String>(_OrderIdentifier_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", name = "PolicyNumbers")
    public JAXBElement<Long> createPolicyNumbers(Long value) {
        return new JAXBElement<Long>(_PolicyNumbers_QNAME, Long.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", name = "RequestIdentifier")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    public JAXBElement<String> createRequestIdentifier(String value) {
        return new JAXBElement<String>(_RequestIdentifier_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", name = "SocialSecurityNumberFormatted")
    public JAXBElement<String> createSocialSecurityNumberFormatted(String value) {
        return new JAXBElement<String>(_SocialSecurityNumberFormatted_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", name = "NationalProviderIdentifier")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    public JAXBElement<String> createNationalProviderIdentifier(String value) {
        return new JAXBElement<String>(_NationalProviderIdentifier_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", name = "ReturnedReoriginatedIdentifier")
    public JAXBElement<String> createReturnedReoriginatedIdentifier(String value) {
        return new JAXBElement<String>(_ReturnedReoriginatedIdentifier_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", name = "EventIdentifier")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    public JAXBElement<String> createEventIdentifier(String value) {
        return new JAXBElement<String>(_EventIdentifier_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", name = "OperatorIdentifier")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    public JAXBElement<String> createOperatorIdentifier(String value) {
        return new JAXBElement<String>(_OperatorIdentifier_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", name = "PersonIdentifier")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    public JAXBElement<String> createPersonIdentifier(String value) {
        return new JAXBElement<String>(_PersonIdentifier_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", name = "SocialSecurityNumber")
    public JAXBElement<Long> createSocialSecurityNumber(Long value) {
        return new JAXBElement<Long>(_SocialSecurityNumber_QNAME, Long.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", name = "MedicareIdentifier")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    public JAXBElement<String> createMedicareIdentifier(String value) {
        return new JAXBElement<String>(_MedicareIdentifier_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", name = "AccountNumber")
    public JAXBElement<String> createAccountNumber(String value) {
        return new JAXBElement<String>(_AccountNumber_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", name = "NetworkIdentifier")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    public JAXBElement<String> createNetworkIdentifier(String value) {
        return new JAXBElement<String>(_NetworkIdentifier_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", name = "NachaResponseIdentifier")
    public JAXBElement<String> createNachaResponseIdentifier(String value) {
        return new JAXBElement<String>(_NachaResponseIdentifier_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", name = "NoteIdentifier")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    public JAXBElement<String> createNoteIdentifier(String value) {
        return new JAXBElement<String>(_NoteIdentifier_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", name = "BusinessIdentifier")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    public JAXBElement<String> createBusinessIdentifier(String value) {
        return new JAXBElement<String>(_BusinessIdentifier_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", name = "TaxIdentifierNumber")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    public JAXBElement<String> createTaxIdentifierNumber(String value) {
        return new JAXBElement<String>(_TaxIdentifierNumber_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", name = "AudioIdentifier")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    public JAXBElement<String> createAudioIdentifier(String value) {
        return new JAXBElement<String>(_AudioIdentifier_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", name = "PayerPrimaryIdentifier")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    public JAXBElement<String> createPayerPrimaryIdentifier(String value) {
        return new JAXBElement<String>(_PayerPrimaryIdentifier_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", name = "LegacyIdentifier")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    public JAXBElement<String> createLegacyIdentifier(String value) {
        return new JAXBElement<String>(_LegacyIdentifier_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", name = "ImageIdentifier")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    public JAXBElement<String> createImageIdentifier(String value) {
        return new JAXBElement<String>(_ImageIdentifier_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", name = "UniqueUniversalIdentifier")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    public JAXBElement<String> createUniqueUniversalIdentifier(String value) {
        return new JAXBElement<String>(_UniqueUniversalIdentifier_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", name = "OptumAssignedGroupIdentifier")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    public JAXBElement<String> createOptumAssignedGroupIdentifier(String value) {
        return new JAXBElement<String>(_OptumAssignedGroupIdentifier_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", name = "OptumAssignedSubGroupIdentifier")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    public JAXBElement<String> createOptumAssignedSubGroupIdentifier(String value) {
        return new JAXBElement<String>(_OptumAssignedSubGroupIdentifier_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", name = "MedicaidIdentifier")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    public JAXBElement<String> createMedicaidIdentifier(String value) {
        return new JAXBElement<String>(_MedicaidIdentifier_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", name = "SenderAssignedSubscriberIdentifier")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    public JAXBElement<String> createSenderAssignedSubscriberIdentifier(String value) {
        return new JAXBElement<String>(_SenderAssignedSubscriberIdentifier_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", name = "VideoIdentifier")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    public JAXBElement<String> createVideoIdentifier(String value) {
        return new JAXBElement<String>(_VideoIdentifier_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", name = "MembershipOwnerIdentifier")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    public JAXBElement<String> createMembershipOwnerIdentifier(String value) {
        return new JAXBElement<String>(_MembershipOwnerIdentifier_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", name = "TextIdentifier")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    public JAXBElement<String> createTextIdentifier(String value) {
        return new JAXBElement<String>(_TextIdentifier_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", name = "PaymentMethodIdentifier")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    public JAXBElement<String> createPaymentMethodIdentifier(String value) {
        return new JAXBElement<String>(_PaymentMethodIdentifier_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", name = "OptumAssignedMemberIdentifier")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    public JAXBElement<String> createOptumAssignedMemberIdentifier(String value) {
        return new JAXBElement<String>(_OptumAssignedMemberIdentifier_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", name = "CustomerNotificationIdentifier")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    public JAXBElement<String> createCustomerNotificationIdentifier(String value) {
        return new JAXBElement<String>(_CustomerNotificationIdentifier_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UniqueIdentifier }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", name = "UniqueIdentifiers")
    public JAXBElement<UniqueIdentifier> createUniqueIdentifiers(UniqueIdentifier value) {
        return new JAXBElement<UniqueIdentifier>(_UniqueIdentifiers_QNAME, UniqueIdentifier.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", name = "ConsolidatedPaymentDetailIdentifier")
    public JAXBElement<String> createConsolidatedPaymentDetailIdentifier(String value) {
        return new JAXBElement<String>(_ConsolidatedPaymentDetailIdentifier_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", name = "SenderAssignedGroupIdentifier")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    public JAXBElement<String> createSenderAssignedGroupIdentifier(String value) {
        return new JAXBElement<String>(_SenderAssignedGroupIdentifier_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", name = "PolicyNumber")
    public JAXBElement<Long> createPolicyNumber(Long value) {
        return new JAXBElement<Long>(_PolicyNumber_QNAME, Long.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", name = "ClientIdentifier")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    public JAXBElement<String> createClientIdentifier(String value) {
        return new JAXBElement<String>(_ClientIdentifier_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", name = "NewBankRoutingNumber")
    public JAXBElement<Long> createNewBankRoutingNumber(Long value) {
        return new JAXBElement<Long>(_NewBankRoutingNumber_QNAME, Long.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", name = "BenefitIdentifier")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    public JAXBElement<String> createBenefitIdentifier(String value) {
        return new JAXBElement<String>(_BenefitIdentifier_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", name = "BankAccountNumber")
    public JAXBElement<Long> createBankAccountNumber(Long value) {
        return new JAXBElement<Long>(_BankAccountNumber_QNAME, Long.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", name = "CostCenterIdentifier")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    public JAXBElement<String> createCostCenterIdentifier(String value) {
        return new JAXBElement<String>(_CostCenterIdentifier_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ClientHealthCoverageIdentifier }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", name = "ClientHealthCoverageIdentifier")
    public JAXBElement<ClientHealthCoverageIdentifier> createClientHealthCoverageIdentifier(ClientHealthCoverageIdentifier value) {
        return new JAXBElement<ClientHealthCoverageIdentifier>(_ClientHealthCoverageIdentifier_QNAME, ClientHealthCoverageIdentifier.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", name = "HealthPlanOwnerIdentifier")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    public JAXBElement<String> createHealthPlanOwnerIdentifier(String value) {
        return new JAXBElement<String>(_HealthPlanOwnerIdentifier_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", name = "OptumAssignedPlanIdentifier")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    public JAXBElement<String> createOptumAssignedPlanIdentifier(String value) {
        return new JAXBElement<String>(_OptumAssignedPlanIdentifier_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", name = "TransactionIdentifier")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    public JAXBElement<String> createTransactionIdentifier(String value) {
        return new JAXBElement<String>(_TransactionIdentifier_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", name = "OptumAssignedAgentIdentifier")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    public JAXBElement<String> createOptumAssignedAgentIdentifier(String value) {
        return new JAXBElement<String>(_OptumAssignedAgentIdentifier_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", name = "SenderAssignedMemberIdentifier")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    public JAXBElement<String> createSenderAssignedMemberIdentifier(String value) {
        return new JAXBElement<String>(_SenderAssignedMemberIdentifier_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", name = "HealthCardIdentifier")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    public JAXBElement<String> createHealthCardIdentifier(String value) {
        return new JAXBElement<String>(_HealthCardIdentifier_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", name = "MemberIdentifier")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    public JAXBElement<String> createMemberIdentifier(String value) {
        return new JAXBElement<String>(_MemberIdentifier_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", name = "SubscriberIdentifier")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    public JAXBElement<String> createSubscriberIdentifier(String value) {
        return new JAXBElement<String>(_SubscriberIdentifier_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", name = "PaymentIdentifier")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    public JAXBElement<String> createPaymentIdentifier(String value) {
        return new JAXBElement<String>(_PaymentIdentifier_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", name = "ProductIdentifier")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    public JAXBElement<String> createProductIdentifier(String value) {
        return new JAXBElement<String>(_ProductIdentifier_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", name = "SenderAssignedPlanIdentifier")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    public JAXBElement<String> createSenderAssignedPlanIdentifier(String value) {
        return new JAXBElement<String>(_SenderAssignedPlanIdentifier_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", name = "SocialSecurityNumberEncrypted")
    public JAXBElement<String> createSocialSecurityNumberEncrypted(String value) {
        return new JAXBElement<String>(_SocialSecurityNumberEncrypted_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", name = "PackageIdentifier")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    public JAXBElement<String> createPackageIdentifier(String value) {
        return new JAXBElement<String>(_PackageIdentifier_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", name = "CoordinationOfBenefitsTypeIdentifier")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    public JAXBElement<String> createCoordinationOfBenefitsTypeIdentifier(String value) {
        return new JAXBElement<String>(_CoordinationOfBenefitsTypeIdentifier_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", name = "ClaimIdentifier")
    public JAXBElement<String> createClaimIdentifier(String value) {
        return new JAXBElement<String>(_ClaimIdentifier_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", name = "BillingAccountIdentifier")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    public JAXBElement<String> createBillingAccountIdentifier(String value) {
        return new JAXBElement<String>(_BillingAccountIdentifier_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", name = "PrescriptionNumber")
    public JAXBElement<Long> createPrescriptionNumber(Long value) {
        return new JAXBElement<Long>(_PrescriptionNumber_QNAME, Long.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", name = "PayerIdentifier")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    public JAXBElement<String> createPayerIdentifier(String value) {
        return new JAXBElement<String>(_PayerIdentifier_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", name = "HomePlanIdentifier")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    public JAXBElement<String> createHomePlanIdentifier(String value) {
        return new JAXBElement<String>(_HomePlanIdentifier_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", name = "PlanIdentifier")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    public JAXBElement<String> createPlanIdentifier(String value) {
        return new JAXBElement<String>(_PlanIdentifier_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", name = "PatientIdentifier")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    public JAXBElement<String> createPatientIdentifier(String value) {
        return new JAXBElement<String>(_PatientIdentifier_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", name = "ProviderEnrollmentIdentifier")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    public JAXBElement<String> createProviderEnrollmentIdentifier(String value) {
        return new JAXBElement<String>(_ProviderEnrollmentIdentifier_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", name = "BankRoutingNumber")
    public JAXBElement<Long> createBankRoutingNumber(Long value) {
        return new JAXBElement<Long>(_BankRoutingNumber_QNAME, Long.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", name = "BasePlanIdentifier")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    public JAXBElement<String> createBasePlanIdentifier(String value) {
        return new JAXBElement<String>(_BasePlanIdentifier_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", name = "AgentIdentifier")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    public JAXBElement<String> createAgentIdentifier(String value) {
        return new JAXBElement<String>(_AgentIdentifier_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", name = "NewBankAccountNumber")
    public JAXBElement<Long> createNewBankAccountNumber(Long value) {
        return new JAXBElement<Long>(_NewBankAccountNumber_QNAME, Long.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", name = "ConfirmationNumber")
    public JAXBElement<Long> createConfirmationNumber(Long value) {
        return new JAXBElement<Long>(_ConfirmationNumber_QNAME, Long.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", name = "CorrelationIdentifier")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    public JAXBElement<String> createCorrelationIdentifier(String value) {
        return new JAXBElement<String>(_CorrelationIdentifier_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", name = "UserIdentifier")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    public JAXBElement<String> createUserIdentifier(String value) {
        return new JAXBElement<String>(_UserIdentifier_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", name = "RecipientConfigurationIdentifier")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    public JAXBElement<String> createRecipientConfigurationIdentifier(String value) {
        return new JAXBElement<String>(_RecipientConfigurationIdentifier_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", name = "GroupIdentifier")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    public JAXBElement<String> createGroupIdentifier(String value) {
        return new JAXBElement<String>(_GroupIdentifier_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", name = "BillingIdentifier")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    public JAXBElement<String> createBillingIdentifier(String value) {
        return new JAXBElement<String>(_BillingIdentifier_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", name = "OptumAssignedSubscriberIdentifier")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    public JAXBElement<String> createOptumAssignedSubscriberIdentifier(String value) {
        return new JAXBElement<String>(_OptumAssignedSubscriberIdentifier_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", name = "BillingGroupIdentifiers")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    public JAXBElement<String> createBillingGroupIdentifiers(String value) {
        return new JAXBElement<String>(_BillingGroupIdentifiers_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", name = "CreditCardBillingIdentifier")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    public JAXBElement<String> createCreditCardBillingIdentifier(String value) {
        return new JAXBElement<String>(_CreditCardBillingIdentifier_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", name = "SubGroupIdentifier")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    public JAXBElement<String> createSubGroupIdentifier(String value) {
        return new JAXBElement<String>(_SubGroupIdentifier_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", name = "Identifier")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    public JAXBElement<String> createIdentifier(String value) {
        return new JAXBElement<String>(_Identifier_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", name = "ProviderIdentifier")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    public JAXBElement<String> createProviderIdentifier(String value) {
        return new JAXBElement<String>(_ProviderIdentifier_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", name = "CheckNumber")
    public JAXBElement<Long> createCheckNumber(Long value) {
        return new JAXBElement<Long>(_CheckNumber_QNAME, Long.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", name = "SenderAssignedPolicyIdentifier")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    public JAXBElement<String> createSenderAssignedPolicyIdentifier(String value) {
        return new JAXBElement<String>(_SenderAssignedPolicyIdentifier_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", name = "EntityIdentifier")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    public JAXBElement<String> createEntityIdentifier(String value) {
        return new JAXBElement<String>(_EntityIdentifier_QNAME, String.class, null, value);
    }

}
