//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.03 at 12:32:33 PM CDT 
//


package com.optum.enterprise.schema.cim.common.servicemessage_v1_0;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import com.optum.enterprise.schema.cim.common.common_v1_0.HttpLink;
import com.optum.enterprise.schema.cim.common.common_v1_0.Message;
import com.optum.enterprise.schema.cim.common.common_v1_0.SoftwareComponent;


/**
 * 
 * 				This is used for conveying messages with code, description and 
 * 				0 or more Links in Responses. Helpful for RESTful based APIs.
 * 				Optional Errors/Exceptions are also part of messages, along
 * 				with Events.
 * 				
 * 				The code of the message. Within our API we
 * 				should define codes for all of our messages, so 
 * 				that automation of message processing could be 
 * 				enabled.
 * 				<p/>
 * 				The following ranges are specified for message codes:
 * 				<ol>
 * 				<li>
 * 				{@code 1xxx}. Level 1 or Syntactic/UI errors, like invalid characters in a 
 * 				parameter, or invalid date, or a required parameter not specified etc.
 * 				</li>
 * 				<li>
 * 				{@code 2xxx}. Level 2 errors, like XML validation failure, but not business 
 * 				logic related error. These errors are somewhere between syntactic (Level 1)
 * 				errors, and business logic errors (Level 3).
 * 				</li>
 * 				<li>
 * 				{@code 3xxx}. Level 3 errors, like business logic related error. 
 * 				These errors require back-end processing.
 * 				</li>
 * 				<li>
 * 				{@code 5xxx}. Level 5 errors. These errors are unrecoverable, and may require
 * 				manual IT intervention. 
 * 				</li>
 * 				<li>
 * 				{@code 9xxx}. Level 9 errors. These errors are API related. For example, 
 * 				deprecation etc.. 
 * 				</li>
 * 				</ol>
 * 				
 * 			
 * 
 * <p>Java class for ServiceMessage complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ServiceMessage">
 *   &lt;complexContent>
 *     &lt;extension base="{http://enterprise.optum.com/schema/cim/common/Common_v1_0}Message">
 *       &lt;sequence>
 *         &lt;element name="Identifier" type="{http://enterprise.optum.com/schema/cim/common/Common_v1_0}AlphaNumericNonEmptyType" minOccurs="0"/>
 *         &lt;element name="Type" type="{http://enterprise.optum.com/schema/cim/common/ServiceMessage_v1_0}MessageTypeEnum"/>
 *         &lt;element name="Code" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element ref="{http://enterprise.optum.com/schema/cim/common/Common_v1_0}Timestamp" minOccurs="0"/>
 *         &lt;element ref="{http://enterprise.optum.com/schema/cim/common/Common_v1_0}SoftwareComponent" minOccurs="0"/>
 *         &lt;element ref="{http://enterprise.optum.com/schema/cim/common/Common_v1_0}HttpLinks" maxOccurs="500000" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ServiceMessage", propOrder = {
    "identifier",
    "type",
    "code",
    "timestamp",
    "softwareComponent",
    "httpLinks"
})
public class ServiceMessage
    extends Message
{

    @XmlElement(name = "Identifier")
    protected String identifier;
    @XmlElement(name = "Type", required = true)
    protected MessageTypeEnum type;
    @XmlElement(name = "Code", required = true)
    protected BigInteger code;
    @XmlElement(name = "Timestamp", namespace = "http://enterprise.optum.com/schema/cim/common/Common_v1_0")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar timestamp;
    @XmlElement(name = "SoftwareComponent", namespace = "http://enterprise.optum.com/schema/cim/common/Common_v1_0")
    protected SoftwareComponent softwareComponent;
    @XmlElement(name = "HttpLinks", namespace = "http://enterprise.optum.com/schema/cim/common/Common_v1_0")
    protected List<HttpLink> httpLinks;

    /**
     * Gets the value of the identifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdentifier() {
        return identifier;
    }

    /**
     * Sets the value of the identifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdentifier(String value) {
        this.identifier = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link MessageTypeEnum }
     *     
     */
    public MessageTypeEnum getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link MessageTypeEnum }
     *     
     */
    public void setType(MessageTypeEnum value) {
        this.type = value;
    }

    /**
     * Gets the value of the code property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCode() {
        return code;
    }

    /**
     * Sets the value of the code property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCode(BigInteger value) {
        this.code = value;
    }

    /**
     * 
     * 								Server generated time stamp of message
     * 								generation.
     * 							
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTimestamp() {
        return timestamp;
    }

    /**
     * Sets the value of the timestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTimestamp(XMLGregorianCalendar value) {
        this.timestamp = value;
    }

    /**
     * 
     * 								The Software component on which the message was
     * 								generated.
     * 							
     * 
     * @return
     *     possible object is
     *     {@link SoftwareComponent }
     *     
     */
    public SoftwareComponent getSoftwareComponent() {
        return softwareComponent;
    }

    /**
     * Sets the value of the softwareComponent property.
     * 
     * @param value
     *     allowed object is
     *     {@link SoftwareComponent }
     *     
     */
    public void setSoftwareComponent(SoftwareComponent value) {
        this.softwareComponent = value;
    }

    /**
     * 
     * 								The set of Links is optional. They can be used
     * 								to implement HATEOAS (HTTP As The Engine Of 
     * 								Application State).
     * 								This requires API architecture to incorporate 
     * 								this type encoding in the Service provider code.
     * 								Especially useful in REST based APIs.
     * 							Gets the value of the httpLinks property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the httpLinks property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHttpLinks().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link HttpLink }
     * 
     * 
     */
    public List<HttpLink> getHttpLinks() {
        if (httpLinks == null) {
            httpLinks = new ArrayList<HttpLink>();
        }
        return this.httpLinks;
    }

}
