//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.03 at 12:32:33 PM CDT 
//


package com.optum.enterprise.schema.cim.common.common_v1_0;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                 Type specifying Currency based range having a Maximum and 
 *                 Minimum. Types extending this type would have these two 
 *                 attributes in common.
 *             
 * 
 * <p>Java class for AbstractCurrencyRange complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AbstractCurrencyRange">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Minimum" type="{http://enterprise.optum.com/schema/cim/common/Common_v1_0}Currency"/>
 *         &lt;element name="Maximum" type="{http://enterprise.optum.com/schema/cim/common/Common_v1_0}Currency"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AbstractCurrencyRange", propOrder = {
    "minimum",
    "maximum"
})
public abstract class AbstractCurrencyRange {

    @XmlElement(name = "Minimum", required = true)
    protected Currency minimum;
    @XmlElement(name = "Maximum", required = true)
    protected Currency maximum;

    /**
     * Gets the value of the minimum property.
     * 
     * @return
     *     possible object is
     *     {@link Currency }
     *     
     */
    public Currency getMinimum() {
        return minimum;
    }

    /**
     * Sets the value of the minimum property.
     * 
     * @param value
     *     allowed object is
     *     {@link Currency }
     *     
     */
    public void setMinimum(Currency value) {
        this.minimum = value;
    }

    /**
     * Gets the value of the maximum property.
     * 
     * @return
     *     possible object is
     *     {@link Currency }
     *     
     */
    public Currency getMaximum() {
        return maximum;
    }

    /**
     * Sets the value of the maximum property.
     * 
     * @param value
     *     allowed object is
     *     {@link Currency }
     *     
     */
    public void setMaximum(Currency value) {
        this.maximum = value;
    }

}
