//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.03 at 12:32:33 PM CDT 
//


package com.optum.enterprise.schema.cim.common.common_v1_0;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for HttpMimeTypeImageEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="HttpMimeTypeImageEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}normalizedString">
 *     &lt;enumeration value="image/gif"/>
 *     &lt;enumeration value="image/jpeg"/>
 *     &lt;enumeration value="image/png"/>
 *     &lt;enumeration value="image/svg+xml"/>
 *     &lt;enumeration value="image/tiff"/>
 *     &lt;enumeration value="image/x-tiff"/>
 *     &lt;enumeration value="image/bmp"/>
 *     &lt;enumeration value="image/x-windows-bmp"/>
 *     &lt;enumeration value="image/gif"/>
 *     &lt;enumeration value="image/pict"/>
 *     &lt;enumeration value="image/x-quicktime"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "HttpMimeTypeImageEnum")
@XmlEnum
public enum HttpMimeTypeImageEnum {

    @XmlEnumValue("image/gif")
    IMAGE_GIF("image/gif"),
    @XmlEnumValue("image/jpeg")
    IMAGE_JPEG("image/jpeg"),
    @XmlEnumValue("image/png")
    IMAGE_PNG("image/png"),
    @XmlEnumValue("image/svg+xml")
    IMAGE_SVG_XML("image/svg+xml"),
    @XmlEnumValue("image/tiff")
    IMAGE_TIFF("image/tiff"),
    @XmlEnumValue("image/x-tiff")
    IMAGE_X_TIFF("image/x-tiff"),
    @XmlEnumValue("image/bmp")
    IMAGE_BMP("image/bmp"),
    @XmlEnumValue("image/x-windows-bmp")
    IMAGE_X_WINDOWS_BMP("image/x-windows-bmp"),
    @XmlEnumValue("image/pict")
    IMAGE_PICT("image/pict"),
    @XmlEnumValue("image/x-quicktime")
    IMAGE_X_QUICKTIME("image/x-quicktime");
    private final String value;

    HttpMimeTypeImageEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static HttpMimeTypeImageEnum fromValue(String v) {
        for (HttpMimeTypeImageEnum c: HttpMimeTypeImageEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
