//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.03 at 12:32:33 PM CDT 
//


package com.optum.enterprise.schema.cim.common.common_v1_0;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LocaleEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="LocaleEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}normalizedString">
 *     &lt;enumeration value="en"/>
 *     &lt;enumeration value="en-US"/>
 *     &lt;enumeration value="en-CAN"/>
 *     &lt;enumeration value="fr"/>
 *     &lt;enumeration value="fr-CAN"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "LocaleEnum")
@XmlEnum
public enum LocaleEnum {

    @XmlEnumValue("en")
    EN("en"),
    @XmlEnumValue("en-US")
    EN_US("en-US"),
    @XmlEnumValue("en-CAN")
    EN_CAN("en-CAN"),
    @XmlEnumValue("fr")
    FR("fr"),
    @XmlEnumValue("fr-CAN")
    FR_CAN("fr-CAN");
    private final String value;

    LocaleEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static LocaleEnum fromValue(String v) {
        for (LocaleEnum c: LocaleEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
