//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.03 at 12:32:33 PM CDT 
//


package com.optum.enterprise.schema.cim.api.finance.payables.provider.epspaymentmaintenanceservice_v1_0;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for EpsConsolidatedClaimPaymentDetail complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EpsConsolidatedClaimPaymentDetail">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://enterprise.optum.com/schema/cim/api/finance/payables/provider/EpsPaymentMaintenanceService_v1_0}ReoriginatedApFileProcess" minOccurs="0"/>
 *         &lt;element ref="{http://enterprise.optum.com/schema/cim/common/Identifier_v1_0}CheckNumber" minOccurs="0"/>
 *         &lt;element ref="{http://enterprise.optum.com/schema/cim/common/Common_v1_0}CheckDate" minOccurs="0"/>
 *         &lt;element ref="{http://enterprise.optum.com/schema/cim/common/Identifier_v1_0}ConsolidatedPaymentDetailIdentifier" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EpsConsolidatedClaimPaymentDetail", propOrder = {
    "reoriginatedApFileProcess",
    "checkNumber",
    "checkDate",
    "consolidatedPaymentDetailIdentifier"
})
public class EpsConsolidatedClaimPaymentDetail {

    @XmlElement(name = "ReoriginatedApFileProcess")
    protected String reoriginatedApFileProcess;
    @XmlElement(name = "CheckNumber", namespace = "http://enterprise.optum.com/schema/cim/common/Identifier_v1_0")
    protected Long checkNumber;
    @XmlElement(name = "CheckDate", namespace = "http://enterprise.optum.com/schema/cim/common/Common_v1_0")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar checkDate;
    @XmlElement(name = "ConsolidatedPaymentDetailIdentifier", namespace = "http://enterprise.optum.com/schema/cim/common/Identifier_v1_0")
    protected String consolidatedPaymentDetailIdentifier;

    /**
     * Gets the value of the reoriginatedApFileProcess property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReoriginatedApFileProcess() {
        return reoriginatedApFileProcess;
    }

    /**
     * Sets the value of the reoriginatedApFileProcess property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReoriginatedApFileProcess(String value) {
        this.reoriginatedApFileProcess = value;
    }

    /**
     * Gets the value of the checkNumber property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getCheckNumber() {
        return checkNumber;
    }

    /**
     * Sets the value of the checkNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setCheckNumber(Long value) {
        this.checkNumber = value;
    }

    /**
     * Gets the value of the checkDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCheckDate() {
        return checkDate;
    }

    /**
     * Sets the value of the checkDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCheckDate(XMLGregorianCalendar value) {
        this.checkDate = value;
    }

    /**
     * Gets the value of the consolidatedPaymentDetailIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConsolidatedPaymentDetailIdentifier() {
        return consolidatedPaymentDetailIdentifier;
    }

    /**
     * Sets the value of the consolidatedPaymentDetailIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConsolidatedPaymentDetailIdentifier(String value) {
        this.consolidatedPaymentDetailIdentifier = value;
    }

}
