//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.03 at 12:32:33 PM CDT 
//


package com.optum.enterprise.schema.cim.api.finance.payables.provider.epspaymentmaintenanceservice_v1_0;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for EpsConsolidatedClaimPaymentStatusHistory complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EpsConsolidatedClaimPaymentStatusHistory">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://enterprise.optum.com/schema/cim/api/finance/payables/provider/EpsPaymentMaintenanceService_v1_0}VcpReoriginationDate"/>
 *         &lt;element ref="{http://enterprise.optum.com/schema/cim/api/finance/payables/provider/EpsPaymentMaintenanceService_v1_0}PaymentErrorDateTime"/>
 *         &lt;element ref="{http://enterprise.optum.com/schema/cim/api/finance/payables/provider/EpsPaymentMaintenanceService_v1_0}EpsPaymentErrorStatusCode"/>
 *         &lt;element ref="{http://enterprise.optum.com/schema/cim/api/finance/payables/provider/EpsPaymentMaintenanceService_v1_0}EpsPaymentStatusCode"/>
 *         &lt;element ref="{http://enterprise.optum.com/schema/cim/common/Common_v1_0}LastUpdatedByUserLogin"/>
 *         &lt;element ref="{http://enterprise.optum.com/schema/cim/common/Common_v1_0}LastUpdatedOn"/>
 *         &lt;element ref="{http://enterprise.optum.com/schema/cim/api/finance/payables/provider/EpsPaymentMaintenanceService_v1_0}ConsolidatedPaymentNumber"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EpsConsolidatedClaimPaymentStatusHistory", propOrder = {
    "vcpReoriginationDate",
    "paymentErrorDateTime",
    "epsPaymentErrorStatusCode",
    "epsPaymentStatusCode",
    "lastUpdatedByUserLogin",
    "lastUpdatedOn",
    "consolidatedPaymentNumber"
})
public class EpsConsolidatedClaimPaymentStatusHistory {

    @XmlElement(name = "VcpReoriginationDate", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar vcpReoriginationDate;
    @XmlElement(name = "PaymentErrorDateTime", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar paymentErrorDateTime;
    @XmlElement(name = "EpsPaymentErrorStatusCode", required = true)
    protected EpsPaymentStatusCode epsPaymentErrorStatusCode;
    @XmlElement(name = "EpsPaymentStatusCode", required = true)
    protected EpsPaymentStatusCode epsPaymentStatusCode;
    @XmlElement(name = "LastUpdatedByUserLogin", namespace = "http://enterprise.optum.com/schema/cim/common/Common_v1_0", required = true)
    protected String lastUpdatedByUserLogin;
    @XmlElement(name = "LastUpdatedOn", namespace = "http://enterprise.optum.com/schema/cim/common/Common_v1_0", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar lastUpdatedOn;
    @XmlElement(name = "ConsolidatedPaymentNumber", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String consolidatedPaymentNumber;

    /**
     * Gets the value of the vcpReoriginationDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getVcpReoriginationDate() {
        return vcpReoriginationDate;
    }

    /**
     * Sets the value of the vcpReoriginationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setVcpReoriginationDate(XMLGregorianCalendar value) {
        this.vcpReoriginationDate = value;
    }

    /**
     * Gets the value of the paymentErrorDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPaymentErrorDateTime() {
        return paymentErrorDateTime;
    }

    /**
     * Sets the value of the paymentErrorDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPaymentErrorDateTime(XMLGregorianCalendar value) {
        this.paymentErrorDateTime = value;
    }

    /**
     * Gets the value of the epsPaymentErrorStatusCode property.
     * 
     * @return
     *     possible object is
     *     {@link EpsPaymentStatusCode }
     *     
     */
    public EpsPaymentStatusCode getEpsPaymentErrorStatusCode() {
        return epsPaymentErrorStatusCode;
    }

    /**
     * Sets the value of the epsPaymentErrorStatusCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link EpsPaymentStatusCode }
     *     
     */
    public void setEpsPaymentErrorStatusCode(EpsPaymentStatusCode value) {
        this.epsPaymentErrorStatusCode = value;
    }

    /**
     * Gets the value of the epsPaymentStatusCode property.
     * 
     * @return
     *     possible object is
     *     {@link EpsPaymentStatusCode }
     *     
     */
    public EpsPaymentStatusCode getEpsPaymentStatusCode() {
        return epsPaymentStatusCode;
    }

    /**
     * Sets the value of the epsPaymentStatusCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link EpsPaymentStatusCode }
     *     
     */
    public void setEpsPaymentStatusCode(EpsPaymentStatusCode value) {
        this.epsPaymentStatusCode = value;
    }

    /**
     * Gets the value of the lastUpdatedByUserLogin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastUpdatedByUserLogin() {
        return lastUpdatedByUserLogin;
    }

    /**
     * Sets the value of the lastUpdatedByUserLogin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastUpdatedByUserLogin(String value) {
        this.lastUpdatedByUserLogin = value;
    }

    /**
     * Gets the value of the lastUpdatedOn property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLastUpdatedOn() {
        return lastUpdatedOn;
    }

    /**
     * Sets the value of the lastUpdatedOn property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLastUpdatedOn(XMLGregorianCalendar value) {
        this.lastUpdatedOn = value;
    }

    /**
     * Gets the value of the consolidatedPaymentNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConsolidatedPaymentNumber() {
        return consolidatedPaymentNumber;
    }

    /**
     * Sets the value of the consolidatedPaymentNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConsolidatedPaymentNumber(String value) {
        this.consolidatedPaymentNumber = value;
    }

}
