//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.03 at 12:32:33 PM CDT 
//


package com.optum.enterprise.schema.cim.api.finance.payables.provider.epspaymentmaintenanceservice_v1_0;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import com.optum.enterprise.schema.cim.common.code_v1_0.BaseCode;
import com.optum.enterprise.schema.cim.common.common_v1_0.Currency;


/**
 * <p>Java class for EpsClaimService complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EpsClaimService">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ClaimServiceNumber" type="{http://www.w3.org/2001/XMLSchema}unsignedShort"/>
 *         &lt;element ref="{http://enterprise.optum.com/schema/cim/common/Common_v1_0}ServiceStartDate"/>
 *         &lt;element ref="{http://enterprise.optum.com/schema/cim/common/Common_v1_0}ServiceEndDate"/>
 *         &lt;element ref="{http://enterprise.optum.com/schema/cim/common/Common_v1_0}AllowedAmount"/>
 *         &lt;element ref="{http://enterprise.optum.com/schema/cim/api/finance/payables/provider/EpsPaymentMaintenanceService_v1_0}EpsServiceDescription" minOccurs="0"/>
 *         &lt;element ref="{http://enterprise.optum.com/schema/cim/api/finance/payables/provider/EpsPaymentMaintenanceService_v1_0}RevenueCodeText"/>
 *         &lt;element ref="{http://enterprise.optum.com/schema/cim/api/finance/payables/provider/EpsPaymentMaintenanceService_v1_0}EpsServiceDateTimeQualifer"/>
 *         &lt;element ref="{http://enterprise.optum.com/schema/cim/api/finance/payables/provider/EpsPaymentMaintenanceService_v1_0}LineItemChargeAmount"/>
 *         &lt;element ref="{http://enterprise.optum.com/schema/cim/api/finance/payables/provider/EpsPaymentMaintenanceService_v1_0}LineItemPaidAmount"/>
 *         &lt;element ref="{http://enterprise.optum.com/schema/cim/api/finance/payables/provider/EpsPaymentMaintenanceService_v1_0}EpsServiceCodeText"/>
 *         &lt;element ref="{http://enterprise.optum.com/schema/cim/api/finance/payables/provider/EpsPaymentMaintenanceService_v1_0}EpsProcedureCodeText"/>
 *         &lt;element ref="{http://enterprise.optum.com/schema/cim/api/finance/payables/provider/EpsPaymentMaintenanceService_v1_0}EpsProcedureModifiedCodeText"/>
 *         &lt;element ref="{http://enterprise.optum.com/schema/cim/api/finance/payables/provider/EpsPaymentMaintenanceService_v1_0}EpsAmountQualifierCode"/>
 *         &lt;element ref="{http://enterprise.optum.com/schema/cim/api/finance/payables/provider/EpsPaymentMaintenanceService_v1_0}ProcessDateTime"/>
 *         &lt;element ref="{http://enterprise.optum.com/schema/cim/api/finance/payables/provider/EpsPaymentMaintenanceService_v1_0}EpsUnitOfServicePaidCount"/>
 *         &lt;element ref="{http://enterprise.optum.com/schema/cim/api/finance/payables/provider/EpsPaymentMaintenanceService_v1_0}EpsCompositeMedicalProcedureIdentifier"/>
 *         &lt;element ref="{http://enterprise.optum.com/schema/cim/api/finance/payables/provider/EpsPaymentMaintenanceService_v1_0}EpsOriginalUnitServiceCount"/>
 *         &lt;element ref="{http://enterprise.optum.com/schema/cim/api/finance/payables/provider/EpsPaymentMaintenanceService_v1_0}EpsClaimServiceReasonCodes" maxOccurs="500000" minOccurs="0"/>
 *         &lt;element ref="{http://enterprise.optum.com/schema/cim/api/finance/payables/provider/EpsPaymentMaintenanceService_v1_0}EpsPayerReferenceIdentifierQualifierCodes" maxOccurs="500000" minOccurs="0"/>
 *         &lt;element ref="{http://enterprise.optum.com/schema/cim/api/finance/payables/provider/EpsPaymentMaintenanceService_v1_0}EpsClaimPaymentServiceAdjustments" maxOccurs="500000" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EpsClaimService", propOrder = {
    "claimServiceNumber",
    "serviceStartDate",
    "serviceEndDate",
    "allowedAmount",
    "epsServiceDescription",
    "revenueCodeText",
    "epsServiceDateTimeQualifer",
    "lineItemChargeAmount",
    "lineItemPaidAmount",
    "epsServiceCodeText",
    "epsProcedureCodeText",
    "epsProcedureModifiedCodeText",
    "epsAmountQualifierCode",
    "processDateTime",
    "epsUnitOfServicePaidCount",
    "epsCompositeMedicalProcedureIdentifier",
    "epsOriginalUnitServiceCount",
    "epsClaimServiceReasonCodes",
    "epsPayerReferenceIdentifierQualifierCodes",
    "epsClaimPaymentServiceAdjustments"
})
public class EpsClaimService {

    @XmlElement(name = "ClaimServiceNumber")
    @XmlSchemaType(name = "unsignedShort")
    protected int claimServiceNumber;
    @XmlElement(name = "ServiceStartDate", namespace = "http://enterprise.optum.com/schema/cim/common/Common_v1_0", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar serviceStartDate;
    @XmlElement(name = "ServiceEndDate", namespace = "http://enterprise.optum.com/schema/cim/common/Common_v1_0", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar serviceEndDate;
    @XmlElement(name = "AllowedAmount", namespace = "http://enterprise.optum.com/schema/cim/common/Common_v1_0", required = true)
    protected Currency allowedAmount;
    @XmlElement(name = "EpsServiceDescription")
    protected String epsServiceDescription;
    @XmlElement(name = "RevenueCodeText", required = true)
    protected String revenueCodeText;
    @XmlElement(name = "EpsServiceDateTimeQualifer", required = true)
    protected String epsServiceDateTimeQualifer;
    @XmlElement(name = "LineItemChargeAmount", required = true)
    protected Currency lineItemChargeAmount;
    @XmlElement(name = "LineItemPaidAmount", required = true)
    protected Currency lineItemPaidAmount;
    @XmlElement(name = "EpsServiceCodeText", required = true)
    protected String epsServiceCodeText;
    @XmlElement(name = "EpsProcedureCodeText", required = true)
    protected String epsProcedureCodeText;
    @XmlElement(name = "EpsProcedureModifiedCodeText", required = true)
    protected String epsProcedureModifiedCodeText;
    @XmlElement(name = "EpsAmountQualifierCode", required = true)
    protected BaseCode epsAmountQualifierCode;
    @XmlElement(name = "ProcessDateTime", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar processDateTime;
    @XmlElement(name = "EpsUnitOfServicePaidCount")
    protected double epsUnitOfServicePaidCount;
    @XmlElement(name = "EpsCompositeMedicalProcedureIdentifier", required = true)
    protected String epsCompositeMedicalProcedureIdentifier;
    @XmlElement(name = "EpsOriginalUnitServiceCount")
    protected double epsOriginalUnitServiceCount;
    @XmlElement(name = "EpsClaimServiceReasonCodes")
    protected List<EpsClaimReasonCode> epsClaimServiceReasonCodes;
    @XmlElement(name = "EpsPayerReferenceIdentifierQualifierCodes")
    protected List<EpsReferenceIdentifierQualifierCode> epsPayerReferenceIdentifierQualifierCodes;
    @XmlElement(name = "EpsClaimPaymentServiceAdjustments")
    protected List<EpsClaimPaymentAdjustment> epsClaimPaymentServiceAdjustments;

    /**
     * Gets the value of the claimServiceNumber property.
     * 
     */
    public int getClaimServiceNumber() {
        return claimServiceNumber;
    }

    /**
     * Sets the value of the claimServiceNumber property.
     * 
     */
    public void setClaimServiceNumber(int value) {
        this.claimServiceNumber = value;
    }

    /**
     * Gets the value of the serviceStartDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getServiceStartDate() {
        return serviceStartDate;
    }

    /**
     * Sets the value of the serviceStartDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setServiceStartDate(XMLGregorianCalendar value) {
        this.serviceStartDate = value;
    }

    /**
     * Gets the value of the serviceEndDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getServiceEndDate() {
        return serviceEndDate;
    }

    /**
     * Sets the value of the serviceEndDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setServiceEndDate(XMLGregorianCalendar value) {
        this.serviceEndDate = value;
    }

    /**
     * Gets the value of the allowedAmount property.
     * 
     * @return
     *     possible object is
     *     {@link Currency }
     *     
     */
    public Currency getAllowedAmount() {
        return allowedAmount;
    }

    /**
     * Sets the value of the allowedAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Currency }
     *     
     */
    public void setAllowedAmount(Currency value) {
        this.allowedAmount = value;
    }

    /**
     * Gets the value of the epsServiceDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEpsServiceDescription() {
        return epsServiceDescription;
    }

    /**
     * Sets the value of the epsServiceDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEpsServiceDescription(String value) {
        this.epsServiceDescription = value;
    }

    /**
     * Gets the value of the revenueCodeText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRevenueCodeText() {
        return revenueCodeText;
    }

    /**
     * Sets the value of the revenueCodeText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRevenueCodeText(String value) {
        this.revenueCodeText = value;
    }

    /**
     * Gets the value of the epsServiceDateTimeQualifer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEpsServiceDateTimeQualifer() {
        return epsServiceDateTimeQualifer;
    }

    /**
     * Sets the value of the epsServiceDateTimeQualifer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEpsServiceDateTimeQualifer(String value) {
        this.epsServiceDateTimeQualifer = value;
    }

    /**
     * Gets the value of the lineItemChargeAmount property.
     * 
     * @return
     *     possible object is
     *     {@link Currency }
     *     
     */
    public Currency getLineItemChargeAmount() {
        return lineItemChargeAmount;
    }

    /**
     * Sets the value of the lineItemChargeAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Currency }
     *     
     */
    public void setLineItemChargeAmount(Currency value) {
        this.lineItemChargeAmount = value;
    }

    /**
     * Gets the value of the lineItemPaidAmount property.
     * 
     * @return
     *     possible object is
     *     {@link Currency }
     *     
     */
    public Currency getLineItemPaidAmount() {
        return lineItemPaidAmount;
    }

    /**
     * Sets the value of the lineItemPaidAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Currency }
     *     
     */
    public void setLineItemPaidAmount(Currency value) {
        this.lineItemPaidAmount = value;
    }

    /**
     * Gets the value of the epsServiceCodeText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEpsServiceCodeText() {
        return epsServiceCodeText;
    }

    /**
     * Sets the value of the epsServiceCodeText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEpsServiceCodeText(String value) {
        this.epsServiceCodeText = value;
    }

    /**
     * Gets the value of the epsProcedureCodeText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEpsProcedureCodeText() {
        return epsProcedureCodeText;
    }

    /**
     * Sets the value of the epsProcedureCodeText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEpsProcedureCodeText(String value) {
        this.epsProcedureCodeText = value;
    }

    /**
     * Gets the value of the epsProcedureModifiedCodeText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEpsProcedureModifiedCodeText() {
        return epsProcedureModifiedCodeText;
    }

    /**
     * Sets the value of the epsProcedureModifiedCodeText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEpsProcedureModifiedCodeText(String value) {
        this.epsProcedureModifiedCodeText = value;
    }

    /**
     * Gets the value of the epsAmountQualifierCode property.
     * 
     * @return
     *     possible object is
     *     {@link BaseCode }
     *     
     */
    public BaseCode getEpsAmountQualifierCode() {
        return epsAmountQualifierCode;
    }

    /**
     * Sets the value of the epsAmountQualifierCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link BaseCode }
     *     
     */
    public void setEpsAmountQualifierCode(BaseCode value) {
        this.epsAmountQualifierCode = value;
    }

    /**
     * Gets the value of the processDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getProcessDateTime() {
        return processDateTime;
    }

    /**
     * Sets the value of the processDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setProcessDateTime(XMLGregorianCalendar value) {
        this.processDateTime = value;
    }

    /**
     * Gets the value of the epsUnitOfServicePaidCount property.
     * 
     */
    public double getEpsUnitOfServicePaidCount() {
        return epsUnitOfServicePaidCount;
    }

    /**
     * Sets the value of the epsUnitOfServicePaidCount property.
     * 
     */
    public void setEpsUnitOfServicePaidCount(double value) {
        this.epsUnitOfServicePaidCount = value;
    }

    /**
     * Gets the value of the epsCompositeMedicalProcedureIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEpsCompositeMedicalProcedureIdentifier() {
        return epsCompositeMedicalProcedureIdentifier;
    }

    /**
     * Sets the value of the epsCompositeMedicalProcedureIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEpsCompositeMedicalProcedureIdentifier(String value) {
        this.epsCompositeMedicalProcedureIdentifier = value;
    }

    /**
     * Gets the value of the epsOriginalUnitServiceCount property.
     * 
     */
    public double getEpsOriginalUnitServiceCount() {
        return epsOriginalUnitServiceCount;
    }

    /**
     * Sets the value of the epsOriginalUnitServiceCount property.
     * 
     */
    public void setEpsOriginalUnitServiceCount(double value) {
        this.epsOriginalUnitServiceCount = value;
    }

    /**
     * Gets the value of the epsClaimServiceReasonCodes property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the epsClaimServiceReasonCodes property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEpsClaimServiceReasonCodes().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EpsClaimReasonCode }
     * 
     * 
     */
    public List<EpsClaimReasonCode> getEpsClaimServiceReasonCodes() {
        if (epsClaimServiceReasonCodes == null) {
            epsClaimServiceReasonCodes = new ArrayList<EpsClaimReasonCode>();
        }
        return this.epsClaimServiceReasonCodes;
    }

    /**
     * Gets the value of the epsPayerReferenceIdentifierQualifierCodes property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the epsPayerReferenceIdentifierQualifierCodes property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEpsPayerReferenceIdentifierQualifierCodes().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EpsReferenceIdentifierQualifierCode }
     * 
     * 
     */
    public List<EpsReferenceIdentifierQualifierCode> getEpsPayerReferenceIdentifierQualifierCodes() {
        if (epsPayerReferenceIdentifierQualifierCodes == null) {
            epsPayerReferenceIdentifierQualifierCodes = new ArrayList<EpsReferenceIdentifierQualifierCode>();
        }
        return this.epsPayerReferenceIdentifierQualifierCodes;
    }

    /**
     * Gets the value of the epsClaimPaymentServiceAdjustments property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the epsClaimPaymentServiceAdjustments property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEpsClaimPaymentServiceAdjustments().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EpsClaimPaymentAdjustment }
     * 
     * 
     */
    public List<EpsClaimPaymentAdjustment> getEpsClaimPaymentServiceAdjustments() {
        if (epsClaimPaymentServiceAdjustments == null) {
            epsClaimPaymentServiceAdjustments = new ArrayList<EpsClaimPaymentAdjustment>();
        }
        return this.epsClaimPaymentServiceAdjustments;
    }

}
