//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.03 at 12:32:33 PM CDT 
//


package com.optum.enterprise.schema.cim.api.finance.payables.provider.epspaymentmaintenanceservice_v1_0;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;
import com.optum.enterprise.schema.cim.common.code_v1_0.BaseCode;
import com.optum.enterprise.schema.cim.common.phone_v1_0.Phone;


/**
 * <p>Java class for EpsPayer complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EpsPayer">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://enterprise.optum.com/schema/cim/api/finance/payables/provider/EpsPaymentMaintenanceService_v1_0}EpsPrimaryPayerIdentifier"/>
 *         &lt;element ref="{http://enterprise.optum.com/schema/cim/api/finance/payables/provider/EpsPaymentMaintenanceService_v1_0}EpsSecondaryPayerReferenceIdentifierQualifierCode"/>
 *         &lt;element ref="{http://enterprise.optum.com/schema/cim/api/finance/payables/provider/EpsPaymentMaintenanceService_v1_0}PayerContactName"/>
 *         &lt;element ref="{http://enterprise.optum.com/schema/cim/api/finance/payables/provider/EpsPaymentMaintenanceService_v1_0}PayerContactPhone"/>
 *         &lt;element ref="{http://enterprise.optum.com/schema/cim/api/finance/payables/provider/EpsPaymentMaintenanceService_v1_0}EpsPayerQualifierReference"/>
 *         &lt;element ref="{http://enterprise.optum.com/schema/cim/api/finance/payables/provider/EpsPaymentMaintenanceService_v1_0}ProcessDateTime"/>
 *         &lt;element ref="{http://enterprise.optum.com/schema/cim/api/finance/payables/provider/EpsPaymentMaintenanceService_v1_0}PayerSecondaryIdentifierOriginal"/>
 *         &lt;element ref="{http://enterprise.optum.com/schema/cim/api/finance/payables/provider/EpsPaymentMaintenanceService_v1_0}PayerTechnicalContactName"/>
 *         &lt;element ref="{http://enterprise.optum.com/schema/cim/api/finance/payables/provider/EpsPaymentMaintenanceService_v1_0}PayerTechnicalContactCode"/>
 *         &lt;element ref="{http://enterprise.optum.com/schema/cim/api/finance/payables/provider/EpsPaymentMaintenanceService_v1_0}PayerTechnicalContactEmail"/>
 *         &lt;element ref="{http://enterprise.optum.com/schema/cim/api/finance/payables/provider/EpsPaymentMaintenanceService_v1_0}PayerTechnicalContactWebAddress"/>
 *         &lt;element ref="{http://enterprise.optum.com/schema/cim/api/finance/payables/provider/EpsPaymentMaintenanceService_v1_0}PayerTechnicalContactPhone"/>
 *         &lt;element ref="{http://enterprise.optum.com/schema/cim/api/finance/payables/provider/EpsPaymentMaintenanceService_v1_0}PayerWebAddress"/>
 *         &lt;element ref="{http://enterprise.optum.com/schema/cim/api/finance/payables/provider/EpsPaymentMaintenanceService_v1_0}RemittanceDeliveryMethod"/>
 *         &lt;element ref="{http://enterprise.optum.com/schema/cim/api/finance/payables/provider/EpsPaymentMaintenanceService_v1_0}RemittanceDeliveryMethodName"/>
 *         &lt;element ref="{http://enterprise.optum.com/schema/cim/api/finance/payables/provider/EpsPaymentMaintenanceService_v1_0}RemittanceDeliveryMethodCode"/>
 *         &lt;element ref="{http://enterprise.optum.com/schema/cim/api/finance/payables/provider/EpsPaymentMaintenanceService_v1_0}PayerCountryCodeText"/>
 *         &lt;element ref="{http://enterprise.optum.com/schema/cim/api/finance/payables/provider/EpsPaymentMaintenanceService_v1_0}PayerCountrySubCodeText"/>
 *         &lt;element ref="{http://enterprise.optum.com/schema/cim/api/finance/payables/provider/EpsPaymentMaintenanceService_v1_0}EpsBankingPayerTaxIdentifierNumber" minOccurs="0"/>
 *         &lt;element ref="{http://enterprise.optum.com/schema/cim/api/finance/payables/provider/EpsPaymentMaintenanceService_v1_0}EpsBankingSubPayerIdentifier" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EpsPayer", propOrder = {
    "epsPrimaryPayerIdentifier",
    "epsSecondaryPayerReferenceIdentifierQualifierCode",
    "payerContactName",
    "payerContactPhone",
    "epsPayerQualifierReference",
    "processDateTime",
    "payerSecondaryIdentifierOriginal",
    "payerTechnicalContactName",
    "payerTechnicalContactCode",
    "payerTechnicalContactEmail",
    "payerTechnicalContactWebAddress",
    "payerTechnicalContactPhone",
    "payerWebAddress",
    "remittanceDeliveryMethod",
    "remittanceDeliveryMethodName",
    "remittanceDeliveryMethodCode",
    "payerCountryCodeText",
    "payerCountrySubCodeText",
    "epsBankingPayerTaxIdentifierNumber",
    "epsBankingSubPayerIdentifier"
})
public class EpsPayer {

    @XmlElement(name = "EpsPrimaryPayerIdentifier", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String epsPrimaryPayerIdentifier;
    @XmlElement(name = "EpsSecondaryPayerReferenceIdentifierQualifierCode", required = true)
    protected EpsReferenceIdentifierQualifierCode epsSecondaryPayerReferenceIdentifierQualifierCode;
    @XmlElement(name = "PayerContactName", required = true)
    protected String payerContactName;
    @XmlElement(name = "PayerContactPhone", required = true)
    protected Phone payerContactPhone;
    @XmlElement(name = "EpsPayerQualifierReference", required = true)
    protected String epsPayerQualifierReference;
    @XmlElement(name = "ProcessDateTime", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar processDateTime;
    @XmlElement(name = "PayerSecondaryIdentifierOriginal", required = true)
    protected String payerSecondaryIdentifierOriginal;
    @XmlElement(name = "PayerTechnicalContactName", required = true)
    protected String payerTechnicalContactName;
    @XmlElement(name = "PayerTechnicalContactCode", required = true)
    protected BaseCode payerTechnicalContactCode;
    @XmlElement(name = "PayerTechnicalContactEmail", required = true)
    protected String payerTechnicalContactEmail;
    @XmlElement(name = "PayerTechnicalContactWebAddress", required = true)
    protected String payerTechnicalContactWebAddress;
    @XmlElement(name = "PayerTechnicalContactPhone", required = true)
    protected Phone payerTechnicalContactPhone;
    @XmlElement(name = "PayerWebAddress", required = true)
    protected String payerWebAddress;
    @XmlElement(name = "RemittanceDeliveryMethod", required = true)
    protected String remittanceDeliveryMethod;
    @XmlElement(name = "RemittanceDeliveryMethodName", required = true)
    protected String remittanceDeliveryMethodName;
    @XmlElement(name = "RemittanceDeliveryMethodCode", required = true)
    protected BaseCode remittanceDeliveryMethodCode;
    @XmlElement(name = "PayerCountryCodeText", required = true)
    protected String payerCountryCodeText;
    @XmlElement(name = "PayerCountrySubCodeText", required = true)
    protected String payerCountrySubCodeText;
    @XmlElement(name = "EpsBankingPayerTaxIdentifierNumber")
    protected String epsBankingPayerTaxIdentifierNumber;
    @XmlElement(name = "EpsBankingSubPayerIdentifier")
    protected String epsBankingSubPayerIdentifier;

    /**
     * Gets the value of the epsPrimaryPayerIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEpsPrimaryPayerIdentifier() {
        return epsPrimaryPayerIdentifier;
    }

    /**
     * Sets the value of the epsPrimaryPayerIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEpsPrimaryPayerIdentifier(String value) {
        this.epsPrimaryPayerIdentifier = value;
    }

    /**
     * Gets the value of the epsSecondaryPayerReferenceIdentifierQualifierCode property.
     * 
     * @return
     *     possible object is
     *     {@link EpsReferenceIdentifierQualifierCode }
     *     
     */
    public EpsReferenceIdentifierQualifierCode getEpsSecondaryPayerReferenceIdentifierQualifierCode() {
        return epsSecondaryPayerReferenceIdentifierQualifierCode;
    }

    /**
     * Sets the value of the epsSecondaryPayerReferenceIdentifierQualifierCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link EpsReferenceIdentifierQualifierCode }
     *     
     */
    public void setEpsSecondaryPayerReferenceIdentifierQualifierCode(EpsReferenceIdentifierQualifierCode value) {
        this.epsSecondaryPayerReferenceIdentifierQualifierCode = value;
    }

    /**
     * Gets the value of the payerContactName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPayerContactName() {
        return payerContactName;
    }

    /**
     * Sets the value of the payerContactName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPayerContactName(String value) {
        this.payerContactName = value;
    }

    /**
     * Gets the value of the payerContactPhone property.
     * 
     * @return
     *     possible object is
     *     {@link Phone }
     *     
     */
    public Phone getPayerContactPhone() {
        return payerContactPhone;
    }

    /**
     * Sets the value of the payerContactPhone property.
     * 
     * @param value
     *     allowed object is
     *     {@link Phone }
     *     
     */
    public void setPayerContactPhone(Phone value) {
        this.payerContactPhone = value;
    }

    /**
     * Gets the value of the epsPayerQualifierReference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEpsPayerQualifierReference() {
        return epsPayerQualifierReference;
    }

    /**
     * Sets the value of the epsPayerQualifierReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEpsPayerQualifierReference(String value) {
        this.epsPayerQualifierReference = value;
    }

    /**
     * Gets the value of the processDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getProcessDateTime() {
        return processDateTime;
    }

    /**
     * Sets the value of the processDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setProcessDateTime(XMLGregorianCalendar value) {
        this.processDateTime = value;
    }

    /**
     * Gets the value of the payerSecondaryIdentifierOriginal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPayerSecondaryIdentifierOriginal() {
        return payerSecondaryIdentifierOriginal;
    }

    /**
     * Sets the value of the payerSecondaryIdentifierOriginal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPayerSecondaryIdentifierOriginal(String value) {
        this.payerSecondaryIdentifierOriginal = value;
    }

    /**
     * Gets the value of the payerTechnicalContactName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPayerTechnicalContactName() {
        return payerTechnicalContactName;
    }

    /**
     * Sets the value of the payerTechnicalContactName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPayerTechnicalContactName(String value) {
        this.payerTechnicalContactName = value;
    }

    /**
     * Gets the value of the payerTechnicalContactCode property.
     * 
     * @return
     *     possible object is
     *     {@link BaseCode }
     *     
     */
    public BaseCode getPayerTechnicalContactCode() {
        return payerTechnicalContactCode;
    }

    /**
     * Sets the value of the payerTechnicalContactCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link BaseCode }
     *     
     */
    public void setPayerTechnicalContactCode(BaseCode value) {
        this.payerTechnicalContactCode = value;
    }

    /**
     * Gets the value of the payerTechnicalContactEmail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPayerTechnicalContactEmail() {
        return payerTechnicalContactEmail;
    }

    /**
     * Sets the value of the payerTechnicalContactEmail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPayerTechnicalContactEmail(String value) {
        this.payerTechnicalContactEmail = value;
    }

    /**
     * Gets the value of the payerTechnicalContactWebAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPayerTechnicalContactWebAddress() {
        return payerTechnicalContactWebAddress;
    }

    /**
     * Sets the value of the payerTechnicalContactWebAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPayerTechnicalContactWebAddress(String value) {
        this.payerTechnicalContactWebAddress = value;
    }

    /**
     * Gets the value of the payerTechnicalContactPhone property.
     * 
     * @return
     *     possible object is
     *     {@link Phone }
     *     
     */
    public Phone getPayerTechnicalContactPhone() {
        return payerTechnicalContactPhone;
    }

    /**
     * Sets the value of the payerTechnicalContactPhone property.
     * 
     * @param value
     *     allowed object is
     *     {@link Phone }
     *     
     */
    public void setPayerTechnicalContactPhone(Phone value) {
        this.payerTechnicalContactPhone = value;
    }

    /**
     * Gets the value of the payerWebAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPayerWebAddress() {
        return payerWebAddress;
    }

    /**
     * Sets the value of the payerWebAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPayerWebAddress(String value) {
        this.payerWebAddress = value;
    }

    /**
     * Gets the value of the remittanceDeliveryMethod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRemittanceDeliveryMethod() {
        return remittanceDeliveryMethod;
    }

    /**
     * Sets the value of the remittanceDeliveryMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRemittanceDeliveryMethod(String value) {
        this.remittanceDeliveryMethod = value;
    }

    /**
     * Gets the value of the remittanceDeliveryMethodName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRemittanceDeliveryMethodName() {
        return remittanceDeliveryMethodName;
    }

    /**
     * Sets the value of the remittanceDeliveryMethodName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRemittanceDeliveryMethodName(String value) {
        this.remittanceDeliveryMethodName = value;
    }

    /**
     * Gets the value of the remittanceDeliveryMethodCode property.
     * 
     * @return
     *     possible object is
     *     {@link BaseCode }
     *     
     */
    public BaseCode getRemittanceDeliveryMethodCode() {
        return remittanceDeliveryMethodCode;
    }

    /**
     * Sets the value of the remittanceDeliveryMethodCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link BaseCode }
     *     
     */
    public void setRemittanceDeliveryMethodCode(BaseCode value) {
        this.remittanceDeliveryMethodCode = value;
    }

    /**
     * Gets the value of the payerCountryCodeText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPayerCountryCodeText() {
        return payerCountryCodeText;
    }

    /**
     * Sets the value of the payerCountryCodeText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPayerCountryCodeText(String value) {
        this.payerCountryCodeText = value;
    }

    /**
     * Gets the value of the payerCountrySubCodeText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPayerCountrySubCodeText() {
        return payerCountrySubCodeText;
    }

    /**
     * Sets the value of the payerCountrySubCodeText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPayerCountrySubCodeText(String value) {
        this.payerCountrySubCodeText = value;
    }

    /**
     * Gets the value of the epsBankingPayerTaxIdentifierNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEpsBankingPayerTaxIdentifierNumber() {
        return epsBankingPayerTaxIdentifierNumber;
    }

    /**
     * Sets the value of the epsBankingPayerTaxIdentifierNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEpsBankingPayerTaxIdentifierNumber(String value) {
        this.epsBankingPayerTaxIdentifierNumber = value;
    }

    /**
     * Gets the value of the epsBankingSubPayerIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEpsBankingSubPayerIdentifier() {
        return epsBankingSubPayerIdentifier;
    }

    /**
     * Sets the value of the epsBankingSubPayerIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEpsBankingSubPayerIdentifier(String value) {
        this.epsBankingSubPayerIdentifier = value;
    }

}
