//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.03 at 12:32:33 PM CDT 
//


package com.optum.enterprise.schema.cim.api.finance.payables.provider.epspaymentmaintenanceservice_v1_0;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;
import com.optum.enterprise.schema.cim.common.code_v1_0.BaseCode;
import com.optum.enterprise.schema.cim.common.common_v1_0.Currency;


/**
 * <p>Java class for EpsProviderPaymentAdjustment complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EpsProviderPaymentAdjustment">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://enterprise.optum.com/schema/cim/api/finance/payables/provider/EpsPaymentMaintenanceService_v1_0}ConsolidatedPaymentNumber"/>
 *         &lt;element ref="{http://enterprise.optum.com/schema/cim/api/finance/payables/provider/EpsPaymentMaintenanceService_v1_0}EpsProviderPaymentAdjustmentReasonCode" minOccurs="0"/>
 *         &lt;element ref="{http://enterprise.optum.com/schema/cim/api/finance/payables/provider/EpsPaymentMaintenanceService_v1_0}EpsProviderPaymentAdjustmentIdentifier" minOccurs="0"/>
 *         &lt;element ref="{http://enterprise.optum.com/schema/cim/api/finance/payables/provider/EpsPaymentMaintenanceService_v1_0}EpsProviderReferenceIdentifier" minOccurs="0"/>
 *         &lt;element ref="{http://enterprise.optum.com/schema/cim/common/Common_v1_0}FiscalPeriodDate"/>
 *         &lt;element ref="{http://enterprise.optum.com/schema/cim/common/Common_v1_0}Amount"/>
 *         &lt;element ref="{http://enterprise.optum.com/schema/cim/api/finance/payables/provider/EpsPaymentMaintenanceService_v1_0}ProcessDateTime"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EpsProviderPaymentAdjustment", propOrder = {
    "consolidatedPaymentNumber",
    "epsProviderPaymentAdjustmentReasonCode",
    "epsProviderPaymentAdjustmentIdentifier",
    "epsProviderReferenceIdentifier",
    "fiscalPeriodDate",
    "amount",
    "processDateTime"
})
public class EpsProviderPaymentAdjustment {

    @XmlElement(name = "ConsolidatedPaymentNumber", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String consolidatedPaymentNumber;
    @XmlElement(name = "EpsProviderPaymentAdjustmentReasonCode")
    protected BaseCode epsProviderPaymentAdjustmentReasonCode;
    @XmlElement(name = "EpsProviderPaymentAdjustmentIdentifier")
    protected String epsProviderPaymentAdjustmentIdentifier;
    @XmlElement(name = "EpsProviderReferenceIdentifier")
    protected String epsProviderReferenceIdentifier;
    @XmlElement(name = "FiscalPeriodDate", namespace = "http://enterprise.optum.com/schema/cim/common/Common_v1_0", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar fiscalPeriodDate;
    @XmlElement(name = "Amount", namespace = "http://enterprise.optum.com/schema/cim/common/Common_v1_0", required = true)
    protected Currency amount;
    @XmlElement(name = "ProcessDateTime", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar processDateTime;

    /**
     * Gets the value of the consolidatedPaymentNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConsolidatedPaymentNumber() {
        return consolidatedPaymentNumber;
    }

    /**
     * Sets the value of the consolidatedPaymentNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConsolidatedPaymentNumber(String value) {
        this.consolidatedPaymentNumber = value;
    }

    /**
     * Gets the value of the epsProviderPaymentAdjustmentReasonCode property.
     * 
     * @return
     *     possible object is
     *     {@link BaseCode }
     *     
     */
    public BaseCode getEpsProviderPaymentAdjustmentReasonCode() {
        return epsProviderPaymentAdjustmentReasonCode;
    }

    /**
     * Sets the value of the epsProviderPaymentAdjustmentReasonCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link BaseCode }
     *     
     */
    public void setEpsProviderPaymentAdjustmentReasonCode(BaseCode value) {
        this.epsProviderPaymentAdjustmentReasonCode = value;
    }

    /**
     * Gets the value of the epsProviderPaymentAdjustmentIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEpsProviderPaymentAdjustmentIdentifier() {
        return epsProviderPaymentAdjustmentIdentifier;
    }

    /**
     * Sets the value of the epsProviderPaymentAdjustmentIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEpsProviderPaymentAdjustmentIdentifier(String value) {
        this.epsProviderPaymentAdjustmentIdentifier = value;
    }

    /**
     * Gets the value of the epsProviderReferenceIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEpsProviderReferenceIdentifier() {
        return epsProviderReferenceIdentifier;
    }

    /**
     * Sets the value of the epsProviderReferenceIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEpsProviderReferenceIdentifier(String value) {
        this.epsProviderReferenceIdentifier = value;
    }

    /**
     * Gets the value of the fiscalPeriodDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFiscalPeriodDate() {
        return fiscalPeriodDate;
    }

    /**
     * Sets the value of the fiscalPeriodDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFiscalPeriodDate(XMLGregorianCalendar value) {
        this.fiscalPeriodDate = value;
    }

    /**
     * Gets the value of the amount property.
     * 
     * @return
     *     possible object is
     *     {@link Currency }
     *     
     */
    public Currency getAmount() {
        return amount;
    }

    /**
     * Sets the value of the amount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Currency }
     *     
     */
    public void setAmount(Currency value) {
        this.amount = value;
    }

    /**
     * Gets the value of the processDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getProcessDateTime() {
        return processDateTime;
    }

    /**
     * Sets the value of the processDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setProcessDateTime(XMLGregorianCalendar value) {
        this.processDateTime = value;
    }

}
