//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.03 at 12:32:33 PM CDT 
//


package com.optum.enterprise.schema.cim.api.finance.payables.provider.epspaymentmaintenanceservice_v1_0;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				
 * 				Steve Vaerten from EPS team says we must follow US naming 
 * 				convention.
 * 				This type is created to satisfy that requirement. Oct, 4, 2016,
 * 				and documented here.
 * 				<p/>
 * 				However, following US naming conventions (First, Middle Last 
 * 				with First and Last required), cannot be used outside
 * 				of US as this convention is only US specific and not followed
 * 				universally. 
 * 				<p/>
 * 				If this convention is to be used, a person named <b>John</b>
 * 				(one name) will be forced to split his name to 
 * 				<b>First Name=Jo</b> and <b>Last Name=Hn</b> or have duplicate 
 * 				<b>First Name=John Last Name=John</b>.
 * 				<p/>
 * 				Moreover, someone whose First Name is not their Given name also 
 * 				cannot fit in this convention without forcing them to either 
 * 				change their name or consider their First Name to be their 
 * 				Given Name.
 * 				<p/>
 * 				None of these aforementioned options are acceptable just to 
 * 				satisfy a US naming	convention, anywhere in the world. 
 * 				<p/?
 * 				If we are forced to make this change by fiat (citing "legal
 * 				requirements"), and use this convention as part of the CIM we 
 * 				will essentially be forcing our customers to change their names 
 * 				as described above if they are to use/buy our software. We 
 * 				subesquently, will not be able to compete in the global software 
 * 				marketplace, outside of the US, and even within it, as there 
 * 				will be other sofwtare providers who will not force their 
 * 				customers to change	their names, just in order to use their 
 * 				software systems or follow a specific Naming Convention which
 * 				cannot cater to Customers' naming convention.
 * 				
 * 			
 * 
 * <p>Java class for PersonNameUS complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PersonNameUS">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DisplayName" type="{http://enterprise.optum.com/schema/cim/common/Person_v1_0}PersonNameDisplayType" minOccurs="0"/>
 *         &lt;element name="Prefix" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://enterprise.optum.com/schema/cim/common/Common_v1_0}AlphaOnlyNonEmptyType">
 *               &lt;maxLength value="10"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element ref="{http://enterprise.optum.com/schema/cim/common/Person_v1_0}FirstName"/>
 *         &lt;element ref="{http://enterprise.optum.com/schema/cim/common/Person_v1_0}MiddleName" minOccurs="0"/>
 *         &lt;element ref="{http://enterprise.optum.com/schema/cim/common/Person_v1_0}LastName"/>
 *         &lt;element name="Suffix" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://enterprise.optum.com/schema/cim/common/Common_v1_0}AlphaOnlyNonEmptyType">
 *               &lt;maxLength value="10"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PersonNameUS", propOrder = {
    "displayName",
    "prefix",
    "firstName",
    "middleName",
    "lastName",
    "suffix"
})
public class PersonNameUS {

    @XmlElement(name = "DisplayName")
    protected String displayName;
    @XmlElement(name = "Prefix")
    protected String prefix;
    @XmlElement(name = "FirstName", namespace = "http://enterprise.optum.com/schema/cim/common/Person_v1_0", required = true)
    protected String firstName;
    @XmlElement(name = "MiddleName", namespace = "http://enterprise.optum.com/schema/cim/common/Person_v1_0")
    protected String middleName;
    @XmlElement(name = "LastName", namespace = "http://enterprise.optum.com/schema/cim/common/Person_v1_0", required = true)
    protected String lastName;
    @XmlElement(name = "Suffix")
    protected String suffix;

    /**
     * Gets the value of the displayName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisplayName() {
        return displayName;
    }

    /**
     * Sets the value of the displayName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisplayName(String value) {
        this.displayName = value;
    }

    /**
     * Gets the value of the prefix property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrefix() {
        return prefix;
    }

    /**
     * Sets the value of the prefix property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrefix(String value) {
        this.prefix = value;
    }

    /**
     * Gets the value of the firstName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * Sets the value of the firstName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFirstName(String value) {
        this.firstName = value;
    }

    /**
     * Gets the value of the middleName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMiddleName() {
        return middleName;
    }

    /**
     * Sets the value of the middleName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMiddleName(String value) {
        this.middleName = value;
    }

    /**
     * Gets the value of the lastName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * Sets the value of the lastName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastName(String value) {
        this.lastName = value;
    }

    /**
     * Gets the value of the suffix property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSuffix() {
        return suffix;
    }

    /**
     * Sets the value of the suffix property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSuffix(String value) {
        this.suffix = value;
    }

}
