//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.03 at 12:32:33 PM CDT 
//


package com.optum.enterprise.schema.cim.common.service_v1_0;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;
import com.optum.enterprise.schema.cim.common.code_v1_0.ProcessingStatusCode;


/**
 * 
 * 				Asynchronous responses, which are sent at later
 * 				stage, and require complex business processes to complete. For
 * 				example	a Student Enrollment Request can generate this type of a
 * 				response at a later stage.
 * 			
 * 
 * <p>Java class for AsynchronousResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AsynchronousResponse">
 *   &lt;complexContent>
 *     &lt;extension base="{http://enterprise.optum.com/schema/cim/common/Service_v1_0}Response">
 *       &lt;sequence>
 *         &lt;group ref="{http://enterprise.optum.com/schema/cim/common/Service_v1_0}RequestResponseIdentfiersGroup"/>
 *         &lt;element ref="{http://enterprise.optum.com/schema/cim/common/Common_v1_0}SentDateTime" minOccurs="0"/>
 *         &lt;element ref="{http://enterprise.optum.com/schema/cim/common/Code_v1_0}ProcessingStatusCode"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AsynchronousResponse", propOrder = {
    "correlationIdentifier",
    "transactionIdentifier",
    "sentDateTime",
    "processingStatusCode"
})
public class AsynchronousResponse
    extends Response
{

    @XmlElement(name = "CorrelationIdentifier", namespace = "http://enterprise.optum.com/schema/cim/common/Identifier_v1_0")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String correlationIdentifier;
    @XmlElement(name = "TransactionIdentifier", namespace = "http://enterprise.optum.com/schema/cim/common/Identifier_v1_0")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String transactionIdentifier;
    @XmlElement(name = "SentDateTime", namespace = "http://enterprise.optum.com/schema/cim/common/Common_v1_0")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar sentDateTime;
    @XmlElement(name = "ProcessingStatusCode", namespace = "http://enterprise.optum.com/schema/cim/common/Code_v1_0", required = true)
    protected ProcessingStatusCode processingStatusCode;

    /**
     * 
     * 						
     * 						This element is to be used for any kind of correlation
     * 						control which may be required where the Response to the
     * 						Request is asynchronous and thus not immediately sent.
     * 						<p/>
     * 						So for example: The Service Provider will always have to
     * 						send a synchronous Response back to the client for every
     * 						Service	Invocation. If the Response suffices (Fire and
     * 						Forget pattern), no Correlation Identifier is required.
     * 						<p/>
     * 						However, if the Request was for	a business process 
     * 						which takes a long term to complete, like Student 
     * 						Enrollment, the Service	Provider will send a generated 
     * 						value for the Correlation Identifier in this field 
     * 						(see Response.CorrelationIdentifier) as 
     * 						the immediate synchronous Response to the Student 
     * 						Enrollment Request. The Service	Consumer can then use 
     * 						this Correlation Identifier as a callback, in the future 
     * 						to correlate the original Student Enrollment Request to 
     * 						the eventual Response when received from the Service 
     * 						Provider, sent asynchronously.
     * 						
     * 					
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCorrelationIdentifier() {
        return correlationIdentifier;
    }

    /**
     * Sets the value of the correlationIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCorrelationIdentifier(String value) {
        this.correlationIdentifier = value;
    }

    /**
     * 
     * 						
     * 						If a Service Consumer wants to track multiple Web
     * 						Service calls to a single unit of work, it should pass
     * 						the same Transaction Identifier for all calls in the
     * 						logical unit of work. 
     * 						<p/>
     * 						If the Service Consumer chooses	not to populate this 
     * 						field (typically the first Web Service call, if the 
     * 						unit of work involves multiple Web Service calls), the 
     * 						Service Provider will assume a new unit of work and 
     * 						generate a new Transaction Identifier. 
     * 						<p/>
     * 						In either case, the Transaction Identifier 
     * 						will be	passed back to the Service Consumer in the 
     * 						Response (see Response.TransactionIdentifier). The
     * 						Service	Provider will also propagate the same 
     * 						Transaction	Identifier to any other Web Service calls 
     * 						it needs to	make internally to satisfy the service 
     * 						functionality (Composite Service scenario e.g Student Enrollment).
     * 						
     * 					
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransactionIdentifier() {
        return transactionIdentifier;
    }

    /**
     * Sets the value of the transactionIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransactionIdentifier(String value) {
        this.transactionIdentifier = value;
    }

    /**
     * 
     * 								Date and time the response was sent.
     * 							
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getSentDateTime() {
        return sentDateTime;
    }

    /**
     * Sets the value of the sentDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setSentDateTime(XMLGregorianCalendar value) {
        this.sentDateTime = value;
    }

    /**
     * 
     * 								Processing Status Code related to the
     * 								corresponding request.
     * 							
     * 
     * @return
     *     possible object is
     *     {@link ProcessingStatusCode }
     *     
     */
    public ProcessingStatusCode getProcessingStatusCode() {
        return processingStatusCode;
    }

    /**
     * Sets the value of the processingStatusCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProcessingStatusCode }
     *     
     */
    public void setProcessingStatusCode(ProcessingStatusCode value) {
        this.processingStatusCode = value;
    }

}
