//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.03 at 12:32:33 PM CDT 
//


package com.optum.enterprise.schema.cim.common.service_v1_0;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ComparatorEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ComparatorEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}normalizedString">
 *     &lt;enumeration value="Equals"/>
 *     &lt;enumeration value="Contains"/>
 *     &lt;enumeration value="StartsWith"/>
 *     &lt;enumeration value="SoundsLike"/>
 *     &lt;enumeration value="FirstCharacterMatches"/>
 *     &lt;enumeration value="Greater"/>
 *     &lt;enumeration value="GreaterOrEqual"/>
 *     &lt;enumeration value="Lesser"/>
 *     &lt;enumeration value="LesserOrEqual"/>
 *     &lt;enumeration value="NotEqual"/>
 *     &lt;enumeration value="Between"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ComparatorEnum")
@XmlEnum
public enum ComparatorEnum {

    @XmlEnumValue("Equals")
    EQUALS("Equals"),
    @XmlEnumValue("Contains")
    CONTAINS("Contains"),
    @XmlEnumValue("StartsWith")
    STARTS_WITH("StartsWith"),
    @XmlEnumValue("SoundsLike")
    SOUNDS_LIKE("SoundsLike"),
    @XmlEnumValue("FirstCharacterMatches")
    FIRST_CHARACTER_MATCHES("FirstCharacterMatches"),
    @XmlEnumValue("Greater")
    GREATER("Greater"),
    @XmlEnumValue("GreaterOrEqual")
    GREATER_OR_EQUAL("GreaterOrEqual"),
    @XmlEnumValue("Lesser")
    LESSER("Lesser"),
    @XmlEnumValue("LesserOrEqual")
    LESSER_OR_EQUAL("LesserOrEqual"),
    @XmlEnumValue("NotEqual")
    NOT_EQUAL("NotEqual"),
    @XmlEnumValue("Between")
    BETWEEN("Between");
    private final String value;

    ComparatorEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ComparatorEnum fromValue(String v) {
        for (ComparatorEnum c: ComparatorEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
