//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.03 at 12:32:33 PM CDT 
//


package com.optum.enterprise.schema.cim.common.service_v1_0;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.optum.enterprise.schema.cim.common.service_v1_0 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _SearchCriteria_QNAME = new QName("http://enterprise.optum.com/schema/cim/common/Service_v1_0", "SearchCriteria");
    private final static QName _Urls_QNAME = new QName("http://enterprise.optum.com/schema/cim/common/Service_v1_0", "Urls");
    private final static QName _Url_QNAME = new QName("http://enterprise.optum.com/schema/cim/common/Service_v1_0", "Url");
    private final static QName _SearchByCriteriaRequest_QNAME = new QName("http://enterprise.optum.com/schema/cim/common/Service_v1_0", "SearchByCriteriaRequest");
    private final static QName _Response_QNAME = new QName("http://enterprise.optum.com/schema/cim/common/Service_v1_0", "Response");
    private final static QName _ParameterMap_QNAME = new QName("http://enterprise.optum.com/schema/cim/common/Service_v1_0", "ParameterMap");
    private final static QName _SecurityToken_QNAME = new QName("http://enterprise.optum.com/schema/cim/common/Service_v1_0", "SecurityToken");
    private final static QName _Audit_QNAME = new QName("http://enterprise.optum.com/schema/cim/common/Service_v1_0", "Audit");
    private final static QName _UrlConfig_QNAME = new QName("http://enterprise.optum.com/schema/cim/common/Service_v1_0", "UrlConfig");
    private final static QName _SearchByIdentifierRequest_QNAME = new QName("http://enterprise.optum.com/schema/cim/common/Service_v1_0", "SearchByIdentifierRequest");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.optum.enterprise.schema.cim.common.service_v1_0
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ConstrainedSearch }
     * 
     */
    public ConstrainedSearch createConstrainedSearch() {
        return new ConstrainedSearch();
    }

    /**
     * Create an instance of {@link SecurityCredential }
     * 
     */
    public SecurityCredential createSecurityCredential() {
        return new SecurityCredential();
    }

    /**
     * Create an instance of {@link SearchCriteria }
     * 
     */
    public SearchCriteria createSearchCriteria() {
        return new SearchCriteria();
    }

    /**
     * Create an instance of {@link UserCredential }
     * 
     */
    public UserCredential createUserCredential() {
        return new UserCredential();
    }

    /**
     * Create an instance of {@link Response }
     * 
     */
    public Response createResponse() {
        return new Response();
    }

    /**
     * Create an instance of {@link MapEntry }
     * 
     */
    public MapEntry createMapEntry() {
        return new MapEntry();
    }

    /**
     * Create an instance of {@link ParameterMap }
     * 
     */
    public ParameterMap createParameterMap() {
        return new ParameterMap();
    }

    /**
     * Create an instance of {@link UrlConfig }
     * 
     */
    public UrlConfig createUrlConfig() {
        return new UrlConfig();
    }

    /**
     * Create an instance of {@link Request }
     * 
     */
    public Request createRequest() {
        return new Request();
    }

    /**
     * Create an instance of {@link Audit }
     * 
     */
    public Audit createAudit() {
        return new Audit();
    }

    /**
     * Create an instance of {@link Url }
     * 
     */
    public Url createUrl() {
        return new Url();
    }

    /**
     * Create an instance of {@link SearchByIdentifierRequest }
     * 
     */
    public SearchByIdentifierRequest createSearchByIdentifierRequest() {
        return new SearchByIdentifierRequest();
    }

    /**
     * Create an instance of {@link SearchByCriteriaRequest }
     * 
     */
    public SearchByCriteriaRequest createSearchByCriteriaRequest() {
        return new SearchByCriteriaRequest();
    }

    /**
     * Create an instance of {@link AsynchronousResponse }
     * 
     */
    public AsynchronousResponse createAsynchronousResponse() {
        return new AsynchronousResponse();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SearchCriteria }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://enterprise.optum.com/schema/cim/common/Service_v1_0", name = "SearchCriteria")
    public JAXBElement<SearchCriteria> createSearchCriteria(SearchCriteria value) {
        return new JAXBElement<SearchCriteria>(_SearchCriteria_QNAME, SearchCriteria.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Url }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://enterprise.optum.com/schema/cim/common/Service_v1_0", name = "Urls")
    public JAXBElement<Url> createUrls(Url value) {
        return new JAXBElement<Url>(_Urls_QNAME, Url.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Url }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://enterprise.optum.com/schema/cim/common/Service_v1_0", name = "Url")
    public JAXBElement<Url> createUrl(Url value) {
        return new JAXBElement<Url>(_Url_QNAME, Url.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SearchByCriteriaRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://enterprise.optum.com/schema/cim/common/Service_v1_0", name = "SearchByCriteriaRequest")
    public JAXBElement<SearchByCriteriaRequest> createSearchByCriteriaRequest(SearchByCriteriaRequest value) {
        return new JAXBElement<SearchByCriteriaRequest>(_SearchByCriteriaRequest_QNAME, SearchByCriteriaRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Response }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://enterprise.optum.com/schema/cim/common/Service_v1_0", name = "Response")
    public JAXBElement<Response> createResponse(Response value) {
        return new JAXBElement<Response>(_Response_QNAME, Response.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ParameterMap }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://enterprise.optum.com/schema/cim/common/Service_v1_0", name = "ParameterMap")
    public JAXBElement<ParameterMap> createParameterMap(ParameterMap value) {
        return new JAXBElement<ParameterMap>(_ParameterMap_QNAME, ParameterMap.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://enterprise.optum.com/schema/cim/common/Service_v1_0", name = "SecurityToken")
    public JAXBElement<String> createSecurityToken(String value) {
        return new JAXBElement<String>(_SecurityToken_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Audit }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://enterprise.optum.com/schema/cim/common/Service_v1_0", name = "Audit")
    public JAXBElement<Audit> createAudit(Audit value) {
        return new JAXBElement<Audit>(_Audit_QNAME, Audit.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UrlConfig }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://enterprise.optum.com/schema/cim/common/Service_v1_0", name = "UrlConfig")
    public JAXBElement<UrlConfig> createUrlConfig(UrlConfig value) {
        return new JAXBElement<UrlConfig>(_UrlConfig_QNAME, UrlConfig.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SearchByIdentifierRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://enterprise.optum.com/schema/cim/common/Service_v1_0", name = "SearchByIdentifierRequest")
    public JAXBElement<SearchByIdentifierRequest> createSearchByIdentifierRequest(SearchByIdentifierRequest value) {
        return new JAXBElement<SearchByIdentifierRequest>(_SearchByIdentifierRequest_QNAME, SearchByIdentifierRequest.class, null, value);
    }

}
