//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.03 at 12:32:33 PM CDT 
//


package com.optum.enterprise.schema.cim.common.service_v1_0;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import com.optum.enterprise.schema.cim.common.code_v1_0.ProtocolCode;


/**
 * <p>Java class for Url complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Url">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://enterprise.optum.com/schema/cim/common/Code_v1_0}ProtocolCode"/>
 *         &lt;element ref="{http://enterprise.optum.com/schema/cim/common/Common_v1_0}Host"/>
 *         &lt;element ref="{http://enterprise.optum.com/schema/cim/common/Common_v1_0}Port" minOccurs="0"/>
 *         &lt;element ref="{http://enterprise.optum.com/schema/cim/common/Common_v1_0}Path"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Url", propOrder = {
    "protocolCode",
    "host",
    "port",
    "path"
})
public class Url {

    @XmlElement(name = "ProtocolCode", namespace = "http://enterprise.optum.com/schema/cim/common/Code_v1_0", required = true)
    protected ProtocolCode protocolCode;
    @XmlElement(name = "Host", namespace = "http://enterprise.optum.com/schema/cim/common/Common_v1_0", required = true)
    protected String host;
    @XmlElement(name = "Port", namespace = "http://enterprise.optum.com/schema/cim/common/Common_v1_0")
    protected BigInteger port;
    @XmlElement(name = "Path", namespace = "http://enterprise.optum.com/schema/cim/common/Common_v1_0", required = true)
    protected String path;

    /**
     * Gets the value of the protocolCode property.
     * 
     * @return
     *     possible object is
     *     {@link ProtocolCode }
     *     
     */
    public ProtocolCode getProtocolCode() {
        return protocolCode;
    }

    /**
     * Sets the value of the protocolCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProtocolCode }
     *     
     */
    public void setProtocolCode(ProtocolCode value) {
        this.protocolCode = value;
    }

    /**
     * Gets the value of the host property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHost() {
        return host;
    }

    /**
     * Sets the value of the host property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHost(String value) {
        this.host = value;
    }

    /**
     * Gets the value of the port property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPort() {
        return port;
    }

    /**
     * Sets the value of the port property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPort(BigInteger value) {
        this.port = value;
    }

    /**
     * Gets the value of the path property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPath() {
        return path;
    }

    /**
     * Sets the value of the path property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPath(String value) {
        this.path = value;
    }

}
