//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.03 at 12:32:33 PM CDT 
//


package com.optum.enterprise.schema.cim.common.payer_v1_0;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import com.optum.enterprise.schema.cim.common.entity_v1_0.Entity;


/**
 * 
 * 				A Payer can be a person, or an Organization.
 * 			
 * 
 * <p>Java class for Payer complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Payer">
 *   &lt;complexContent>
 *     &lt;extension base="{http://enterprise.optum.com/schema/cim/common/Entity_v1_0}Entity">
 *       &lt;sequence>
 *         &lt;group ref="{http://enterprise.optum.com/schema/cim/common/Payer_v1_0}PayerSummaryGroup"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Payer", propOrder = {
    "payerPrimaryIdentifier",
    "payerSecondaryIdentifier",
    "taxIdentifierNumber"
})
public class Payer
    extends Entity
{

    @XmlElement(name = "PayerPrimaryIdentifier", namespace = "http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String payerPrimaryIdentifier;
    @XmlElement(name = "PayerSecondaryIdentifier", namespace = "http://enterprise.optum.com/schema/cim/common/Identifier_v1_0")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String payerSecondaryIdentifier;
    @XmlElement(name = "TaxIdentifierNumber", namespace = "http://enterprise.optum.com/schema/cim/common/Identifier_v1_0")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String taxIdentifierNumber;

    /**
     * Gets the value of the payerPrimaryIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPayerPrimaryIdentifier() {
        return payerPrimaryIdentifier;
    }

    /**
     * Sets the value of the payerPrimaryIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPayerPrimaryIdentifier(String value) {
        this.payerPrimaryIdentifier = value;
    }

    /**
     * Gets the value of the payerSecondaryIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPayerSecondaryIdentifier() {
        return payerSecondaryIdentifier;
    }

    /**
     * Sets the value of the payerSecondaryIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPayerSecondaryIdentifier(String value) {
        this.payerSecondaryIdentifier = value;
    }

    /**
     * Gets the value of the taxIdentifierNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxIdentifierNumber() {
        return taxIdentifierNumber;
    }

    /**
     * Sets the value of the taxIdentifierNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxIdentifierNumber(String value) {
        this.taxIdentifierNumber = value;
    }

}
