//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.03 at 12:32:33 PM CDT 
//


package com.optum.enterprise.schema.cim.common.payee_v1_0;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.optum.enterprise.schema.cim.common.payee_v1_0 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _PayeeSummaries_QNAME = new QName("http://enterprise.optum.com/schema/cim/common/Payee_v1_0", "PayeeSummaries");
    private final static QName _PayeeThumbnails_QNAME = new QName("http://enterprise.optum.com/schema/cim/common/Payee_v1_0", "PayeeThumbnails");
    private final static QName _PayeeSummary_QNAME = new QName("http://enterprise.optum.com/schema/cim/common/Payee_v1_0", "PayeeSummary");
    private final static QName _PayeeThumbnail_QNAME = new QName("http://enterprise.optum.com/schema/cim/common/Payee_v1_0", "PayeeThumbnail");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.optum.enterprise.schema.cim.common.payee_v1_0
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PayeeSummary }
     * 
     */
    public PayeeSummary createPayeeSummary() {
        return new PayeeSummary();
    }

    /**
     * Create an instance of {@link Payee }
     * 
     */
    public Payee createPayee() {
        return new Payee();
    }

    /**
     * Create an instance of {@link PayeeThumbnail }
     * 
     */
    public PayeeThumbnail createPayeeThumbnail() {
        return new PayeeThumbnail();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PayeeSummary }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://enterprise.optum.com/schema/cim/common/Payee_v1_0", name = "PayeeSummaries")
    public JAXBElement<PayeeSummary> createPayeeSummaries(PayeeSummary value) {
        return new JAXBElement<PayeeSummary>(_PayeeSummaries_QNAME, PayeeSummary.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PayeeThumbnail }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://enterprise.optum.com/schema/cim/common/Payee_v1_0", name = "PayeeThumbnails")
    public JAXBElement<PayeeThumbnail> createPayeeThumbnails(PayeeThumbnail value) {
        return new JAXBElement<PayeeThumbnail>(_PayeeThumbnails_QNAME, PayeeThumbnail.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PayeeSummary }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://enterprise.optum.com/schema/cim/common/Payee_v1_0", name = "PayeeSummary")
    public JAXBElement<PayeeSummary> createPayeeSummary(PayeeSummary value) {
        return new JAXBElement<PayeeSummary>(_PayeeSummary_QNAME, PayeeSummary.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PayeeThumbnail }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://enterprise.optum.com/schema/cim/common/Payee_v1_0", name = "PayeeThumbnail")
    public JAXBElement<PayeeThumbnail> createPayeeThumbnail(PayeeThumbnail value) {
        return new JAXBElement<PayeeThumbnail>(_PayeeThumbnail_QNAME, PayeeThumbnail.class, null, value);
    }

}
