//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.03 at 12:32:33 PM CDT 
//


package com.optum.enterprise.schema.cim.product.group_v1_0;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.optum.enterprise.schema.cim.product.group_v1_0 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _GroupThumbnails_QNAME = new QName("http://enterprise.optum.com/schema/cim/product/Group_v1_0", "GroupThumbnails");
    private final static QName _GroupThumbnail_QNAME = new QName("http://enterprise.optum.com/schema/cim/product/Group_v1_0", "GroupThumbnail");
    private final static QName _Groups_QNAME = new QName("http://enterprise.optum.com/schema/cim/product/Group_v1_0", "Groups");
    private final static QName _Group_QNAME = new QName("http://enterprise.optum.com/schema/cim/product/Group_v1_0", "Group");
    private final static QName _GroupSummary_QNAME = new QName("http://enterprise.optum.com/schema/cim/product/Group_v1_0", "GroupSummary");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.optum.enterprise.schema.cim.product.group_v1_0
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Group }
     * 
     */
    public Group createGroup() {
        return new Group();
    }

    /**
     * Create an instance of {@link GroupSummary }
     * 
     */
    public GroupSummary createGroupSummary() {
        return new GroupSummary();
    }

    /**
     * Create an instance of {@link GroupThumbnail }
     * 
     */
    public GroupThumbnail createGroupThumbnail() {
        return new GroupThumbnail();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GroupThumbnail }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://enterprise.optum.com/schema/cim/product/Group_v1_0", name = "GroupThumbnails")
    public JAXBElement<GroupThumbnail> createGroupThumbnails(GroupThumbnail value) {
        return new JAXBElement<GroupThumbnail>(_GroupThumbnails_QNAME, GroupThumbnail.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GroupThumbnail }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://enterprise.optum.com/schema/cim/product/Group_v1_0", name = "GroupThumbnail")
    public JAXBElement<GroupThumbnail> createGroupThumbnail(GroupThumbnail value) {
        return new JAXBElement<GroupThumbnail>(_GroupThumbnail_QNAME, GroupThumbnail.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Group }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://enterprise.optum.com/schema/cim/product/Group_v1_0", name = "Groups")
    public JAXBElement<Group> createGroups(Group value) {
        return new JAXBElement<Group>(_Groups_QNAME, Group.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Group }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://enterprise.optum.com/schema/cim/product/Group_v1_0", name = "Group")
    public JAXBElement<Group> createGroup(Group value) {
        return new JAXBElement<Group>(_Group_QNAME, Group.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GroupSummary }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://enterprise.optum.com/schema/cim/product/Group_v1_0", name = "GroupSummary")
    public JAXBElement<GroupSummary> createGroupSummary(GroupSummary value) {
        return new JAXBElement<GroupSummary>(_GroupSummary_QNAME, GroupSummary.class, null, value);
    }

}
