//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.03 at 12:32:33 PM CDT 
//


package com.optum.enterprise.schema.cim.api.finance.payables.provider.paymentupdateservice_v1_0;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import com.optum.enterprise.schema.cim.common.code_v1_0.PaymentMethodCode;


/**
 * <p>Java class for EpsPaymentNachaDetail complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EpsPaymentNachaDetail">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://enterprise.optum.com/schema/cim/common/Identifier_v1_0}NachaResponseIdentifier"/>
 *         &lt;element ref="{http://enterprise.optum.com/schema/cim/api/finance/payables/provider/EpsPaymentMaintenanceService_v1_0}ReturnedPaymentTypeCodeText"/>
 *         &lt;element ref="{http://enterprise.optum.com/schema/cim/common/Code_v1_0}PaymentMethodCode"/>
 *         &lt;element ref="{http://enterprise.optum.com/schema/cim/api/finance/payables/provider/EpsPaymentMaintenanceService_v1_0}ReturnedPaymentStatusCodeText"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EpsPaymentNachaDetail", propOrder = {
    "nachaResponseIdentifier",
    "returnedPaymentTypeCodeText",
    "paymentMethodCode",
    "returnedPaymentStatusCodeText"
})
public class EpsPaymentNachaDetail {

    @XmlElement(name = "NachaResponseIdentifier", namespace = "http://enterprise.optum.com/schema/cim/common/Identifier_v1_0", required = true)
    protected String nachaResponseIdentifier;
    @XmlElement(name = "ReturnedPaymentTypeCodeText", namespace = "http://enterprise.optum.com/schema/cim/api/finance/payables/provider/EpsPaymentMaintenanceService_v1_0", required = true)
    protected String returnedPaymentTypeCodeText;
    @XmlElement(name = "PaymentMethodCode", namespace = "http://enterprise.optum.com/schema/cim/common/Code_v1_0", required = true)
    protected PaymentMethodCode paymentMethodCode;
    @XmlElement(name = "ReturnedPaymentStatusCodeText", namespace = "http://enterprise.optum.com/schema/cim/api/finance/payables/provider/EpsPaymentMaintenanceService_v1_0", required = true)
    protected String returnedPaymentStatusCodeText;

    /**
     * Gets the value of the nachaResponseIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNachaResponseIdentifier() {
        return nachaResponseIdentifier;
    }

    /**
     * Sets the value of the nachaResponseIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNachaResponseIdentifier(String value) {
        this.nachaResponseIdentifier = value;
    }

    /**
     * Gets the value of the returnedPaymentTypeCodeText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReturnedPaymentTypeCodeText() {
        return returnedPaymentTypeCodeText;
    }

    /**
     * Sets the value of the returnedPaymentTypeCodeText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReturnedPaymentTypeCodeText(String value) {
        this.returnedPaymentTypeCodeText = value;
    }

    /**
     * Gets the value of the paymentMethodCode property.
     * 
     * @return
     *     possible object is
     *     {@link PaymentMethodCode }
     *     
     */
    public PaymentMethodCode getPaymentMethodCode() {
        return paymentMethodCode;
    }

    /**
     * Sets the value of the paymentMethodCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaymentMethodCode }
     *     
     */
    public void setPaymentMethodCode(PaymentMethodCode value) {
        this.paymentMethodCode = value;
    }

    /**
     * Gets the value of the returnedPaymentStatusCodeText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReturnedPaymentStatusCodeText() {
        return returnedPaymentStatusCodeText;
    }

    /**
     * Sets the value of the returnedPaymentStatusCodeText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReturnedPaymentStatusCodeText(String value) {
        this.returnedPaymentStatusCodeText = value;
    }

}
